### ISSUE TITLE
No "attendees" and "email column" in "My events"

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#10]
#1303
Frontend
Myevents>there’s no "attendees" and "email column" like written in menue options

**Comment by Heklaterriol** [comment]
Can you provide more details. I do not understand the issue

**Comment by jojo12** [comment]
ok (there is much more in JEM you thought! :-)
You must have attending users!
go to the menu of JEM>myevents>Options:
There are two settings you can choose:
Display attendee column=yes 
and
Display email address=yes
Go to my events! You'll see the attendees column with some numbers like 1/2 +1 ?1 (which have a link)
you choose this link and come to a window "manage attendees"
you can add users, you can delete users, you see the email address of these users, you can print this as a list. 
(if you have the rights from the settings)

**Comment by Heklaterriol** [comment]
you wrote:
_go to the menu of JEM>myevents>Options:
There are two settings you can choose:
Display attendee column=yes_

where exactly are these "my events"-options - I couldn't find them

**Comment by jojo12** [comment]
Go to menu, open the existing menu "my events", open the 2nd tab Options, then you'll see
