### ISSUE TITLE
Settings for Google Map and Community Builder are not visible : hidden settings!

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#100]
Backend>JEMsettings>Eventpage>Choose Map Service -->Display Link to Google Maps : Server not found
Backend>JEMsettings>Global Parameters>Choose Map Service  -->  Display Link to Google Maps : Server not found

**Comment by jojo12** [comment]
and why are the two other fields away?
Backend>JEMsettings>Eventpage>Choose Map Service::

>Top Level Domain of Google Maps Homepage.
>Google Map language

**Comment by jojo12** [comment]
![Map_settings](https://user-images.githubusercontent.com/2960236/221123655-07bd6681-69f3-4606-a152-4f9317f9698d.png)

**Comment by Heklaterriol** [comment]
>> Display Link to Google Maps : Server not found Backend
Cannot reproduce oder find the "Server not found" message. Where does it show up?

**Comment by jojo12** [comment]
JEM4 has not the settings for Display Google Map.
When you choose JEMsettings>Event Page>Venues>Choose Map Service --> Display Link to Google Maps and save
and/or JEMsettings>Global Parameter>Venues>Choose Map Service --> Display Link to Google Maps and save
and go to an event/venue with map, you see the map icon, but linking on it, leads to "Server not found"

**Comment by jojo12** [comment]
or I get

> The Google Maps Embed API must be used in an iframe.

**Comment by Heklaterriol** [comment]
OK.

**1) With "Display link to Google Maps"**
I get an link to Google maps. 
But the URL is the dam like for the embed code, to invalid like: https://maps.google.com/maps?hl=com&q=Matthofring+2%2C+6005+Luzern%2C+CH%2B+%28Testort%29&ie=UTF8&z=15&iwloc=B&output=embed
Google displays the error message "The Google Maps Embed API must be used in an iframe." 

**2) With "Display Google Map"**
Works fine

**3) With "Display Google map (api-key)"**
I get these warnings, but no map is displayed:
```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /www/htdocs/w01374a6/subdomain-access/jem4-test-joomla/j4/components/com_jem/classes/output.class.php on line 964

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /www/htdocs/w01374a6/subdomain-access/jem4-test-joomla/j4/components/com_jem/classes/output.class.php on line 965

Deprecated: Automatic conversion of false to array is deprecated in /www/htdocs/w01374a6/subdomain-access/jem4-test-joomla/j4/libraries/src/HTML/HTMLHelper.php on line 790

Deprecated: Automatic conversion of false to array is deprecated in /www/htdocs/w01374a6/subdomain-access/jem4-test-joomla/j4/libraries/src/HTML/HTMLHelper.php on line 790
```

**Questions / Comments:**
- For "Display link to Google Maps" we just have to correct the link, right?
- What is "Display Google map (api-key)" good for if "Display Google map" works?

**Comment by jojo12** [comment]
My question is: when you can add the additional settings for "Display link to Google Maps" and "Display Google Map"
You can there choose which server e.g. "com" and which Map language e.g. "en" or "de" there would be a better result.

All this works without the api key (it is not working anymore for free, as I think).

**Comment by Heklaterriol** [comment]
For "Display link to Google Maps" the link is not complex: 

The invalid link now is [https://maps.google.com/maps?hl=com&q=Matthofring+2%2C+6005+Luzern%2C+CH%2B+%28Testort%29&ie=UTF8&z=15&iwloc=B&output=embed](https://maps.google.com/maps?hl=com&q=Matthofring+2%2C+6005+Luzern%2C+CH%2B+%28Testort%29&ie=UTF8&z=15&iwloc=B&output=embed)
and it would be sufficient to have
[https://www.google.com/maps/place/Matthofring+2,+6005+Luzern,+Schweiz](https://www.google.com/maps/place/Matthofring+2,+6005+Luzern,+Schweiz)

or if I have coordinates:
[https://www.google.com/maps/place/47°02'06.3"N+8°19'47.7"E](https://www.google.com/maps/place/47°02'06.3"N+8°19'47.7"E)

**Comment by jojo12** [comment]
My question is: why did you forgot the additional settings when I compare with JEM3?

**Comment by jojo12** [comment]
in your JEM3 too, you can find this help:
![mapsettings](https://user-images.githubusercontent.com/2960236/221138144-e7730e36-eacc-41b1-8580-6c90a8ae89bc.png)

**Comment by Heklaterriol** [comment]
> My question is: why did you forgot the additional settings when I compare with JEM3?

The are only hidden and should apear when changing the "Choose Map Service" field. But as you discovered, this is broken.

**Comment by jojo12** [comment]
a solution can be: you add in admin/models/forms/settings.xml the wished standards as default*

**Comment by jojo12** [comment]
one solution can be:
in default_evvenues.php: line 21+22:
`			<li><?php echo $this->form->getLabel('event_tld',$group); ?> <?php echo $this->form->getInput('event_tld',$group); ?></li>
`
and
`<li><?php echo $this->form->getLabel('event_lg',$group); ?> <?php echo $this->form->getInput('event_lg',$group); ?></li>`


in default_evregistration.php line 41:
`			<li ><?php echo $this->form->getLabel('event_comunoption',$group); ?> <?php echo $this->form->getInput('event_comunoption',$group); ?></li>
`

**Comment by Heklaterriol** [comment]
in /com_jem/admin/views/settings/tmpl/default_evregistration.php there is no line 41 …

**Comment by jojo12** [comment]
it must be line 21, sorry!
