### ISSUE TITLE
There is a problem with Tabs in import (misunderstanding)

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#101]
mckillo asked.
There are two tabs, the first tab you see, says **always**, you can only import when nothing is in there. Even when there is nothing.
This tab was for an old (perhaps deprecated) mode to import. I never used it. But it seems the tab title is CSV import,

For CSV import you need the other tab! And this works best

(only the changed times problem is there 12 hours and 02 instead of 00 minutes!)

**Comment by jojo12** [comment]
see help:

Eventlist-Import

Eventlist-Import: The JEM Component will self-discover which version of Eventlist (1.0.1, 1.0.2 or 1.1) is installed on your system.
CSV-Import

CSV-Import: Choose this tab, to import CSV files.

Attention

The order in which you import data in JEM is relevant for its correct working. Advised and tested is: First Venues, then Categories, then Events and then last Cat_Events.
Import Options:

Choose CSV file: Click the file button to choose a local file to import.

Replace if ID exists (otherwise create): Choose yes if you want to overwrite events with already existing IDs want. When no, every event is recreated with a new ID.

Import Events: With this button you can import Events from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

Import Categories: With this button you can import Categories from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

Import Venues: With this button you can import Venues from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

Import Cat_Events: With this button you can import Cat_Events from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

**Comment by jojo12** [comment]
It looks like the titles are exchanged! 
My proposal is to make "active" the "csv-import" and perhaps to change the order of the tabs!

**Comment by jojo12** [comment]
The joomla css is here very bad, but if we make csv-import first and active, this should be solved!

**Comment by jojo12** [comment]
I never used the import from jem 1.0 or 1.1? So I don't know if this will work or if we have to delete it?

**Comment by jojo12** [comment]
It's a problem of the atum administrator template! After all, when there are only two tabs.

**Comment by Heklaterriol** [comment]
I even suggest to simple remove the Eventlist Import. Eventlist was transformed to JEM quite some time ago – end Joomla 1.5. beginning Joomla 2.5
So no tabs at all. Do you agree?

**Comment by jojo12** [comment]
I agree! then we've got two flies!

**Comment by Heklaterriol** [comment]
> I agree! then we've got two flies!

zwei fliegen auf einen Schlag = kill two birds with one stone  :-)

**Comment by jojo12** [comment]
:-)

**Comment by mckillo** [comment]
Done into proposal redesign this import page, see commit  e7a560053dd1fcc4357c2c70f6b80cd5d6e26453
