### ISSUE TITLE
remove Eventlist Import

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#103]
Import Data. Tab and content of "Eventlist Import" is not necessary anymore. We remove this first tab and transform the second tab to a simple page with "CSV Import"
see #101

**Comment by Heklaterriol** [comment]
For a clearer display I would suggest a redesign of "CSV Import" into one column. 

See e.g.:
<img width="444" alt="import" src="https://user-images.githubusercontent.com/28540581/221367989-ba2180df-855f-4fd3-a318-6863a8b18c88.png">

**Comment by mckillo** [comment]
Yes,I agree, but let's me give one more step with a practical proposal in the redesign.
![JEM for JL4 - Redesign import page - proposal more practical](https://user-images.githubusercontent.com/2765316/221400275-f4be191d-4d2e-47ae-bab1-bd6bec9922e6.jpg)

I hope you like it.

**Comment by Heklaterriol** [comment]
Thanks @mckillo, good idea.

**Comment by mckillo** [comment]
During import test, if the events are import from other Joomla, the created and modified user is missing (don't exist), it's normal.

In this import page, is it possible to add combo to asign what user is in created_by

 and modified_by field for each import file.

Proposal 2 for this page, add two text input for user id, see below:

![JEM for JL4 - Redesign import page - proposal v2](https://user-images.githubusercontent.com/2765316/221896120-09ec3acb-442e-4a2b-8a03-a33ac9d4aab0.jpg)

So, the admi can initialize during import process these fields with the ID (if it's defined) in the new JEM installation. 
We avoid having mistakes like this when edit (event, category, venue):

![JEM for JL4 - Error venue edit after import without change id user from other jem installation](https://user-images.githubusercontent.com/2765316/221898075-d88382d7-7f62-4a6d-8da6-4e32e89f4d9e.jpg)

**Comment by mckillo** [comment]
> Thanks @mckillo, good idea.



> For a clearer display I would suggest a redesign of "CSV Import" into one column.
> 
> See e.g.: <img alt="import" width="444" src="https://user-images.githubusercontent.com/28540581/221367989-ba2180df-855f-4fd3-a318-6863a8b18c88.png">

@Keklaterriol: In the night, If you let me, I will send you a commit about your redesign of import page as first step to improvement.

**Comment by mckillo** [comment]
@Keklaterriol: You have already up a new commit to JEM-4beta1 branch. 
See new pull request and I hope everything will be correct (review). You feel free to change what you need.
