### ISSUE TITLE
JEM mailer plugin doesn't load string correctly in the admin view

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#108]
This happens with the previous version (2.3.5) with JL3 and with the beta version (2.3.9) with JL4. It comes inherited.

![JEM for JL4 - Mailer Plugin Admin View doesn't load the string correctly](https://user-images.githubusercontent.com/2765316/222709981-d31da1aa-d171-4b0f-a5f6-b36bfdbede2e.jpg)

**Comment by mckillo** [comment]
Debugging this issue, I have found the origin and the fix.
There is an error in _\plugins\jem\mailer\language\en-GB\en-GB.plg_jem_mailer.ini_

Change this line:
`PLG_JEM_MAILER_LOG_SEND_ERROR="Error sending email to "_QQ_"%s"_QQ_"`

For this one:
`PLG_JEM_MAILER_LOG_SEND_ERROR="Error sending email to '_QQ_'%s'_QQ_'"`

So, all strings are loaded and JEM mailer plugin admin view works in both JEM version.

**Comment by mckillo** [comment]
Fix and up by commit 75bfef3e473d9a47f7e3a0421d69b109516c1b1f

**Comment by jojo12** [comment]
I tested, was a bug and with your commit it will be fine! Thanks

**Comment by Heklaterriol** [comment]
Let's collect the issues with "known solution" and fix them after the coder has finished his work – to prevent interference and confusion.
