### ISSUE TITLE
venueslist is not yet responsive

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#113]
I adapted venueslist so the responsive css can work on it.
Where can I post this?

**Comment by Heklaterriol** [comment]
Put the code in this branch https://github.com/Heklaterriol/JEM-Project/tree/small-fixes-before-JEM4

**Comment by jojo12** [comment]
test.txt: "How can I create a new folder "responsive" to upload there 2 new files?"
