### ISSUE TITLE
Module mod_jem doesn't use default.php (override module doens't work)

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#115]
In JEM 2.3.5, the JEM Basic module (mod_jem) used mod_jem\tmpl\default.php to define the view of the module. We could overwrite the module or customize code of the module view.
Now, in 2.3.9 for J4, this module doesn't use default.php (this file exists). The HTML code of the module is generated for site\components\com_jem\classes\output.class.php by function formatDateTime, an doesn't use tmpl\default.php.
I can't create a custom defalt.php or override of this module in the template.
Is it possible to use default.php of this module to create HTML view?

**Comment by Heklaterriol** [comment]
It is necessary to have the possibility for overrides in JEM Basic module.

How do we change this?

(and why did it change from J3 to J4?)

**Comment by Heklaterriol** [comment]
Just checked. In my installation the mod_jem override works.

with "Default (Responsive Style)" it uses `/templates/cassiopeia/html/mod_jem/responsive/**default.php**`
with "Legacy (Table Style)" it uses `/templates/cassiopeia/html/mod_jem/**default.php**`

**Comment by mckillo** [comment]
Yes, you can do override of mod_jem, but module doesn't use default.php to generate HTML of module.

**Comment by mckillo** [comment]
Sorry Hekla, but I thought that module layout was default by default, I don't know that JEM component setiing define it for JEM module. I have had to review the code to understand it.
I check that if JEM setting - Layout Style = Legacy (TableStyle) is default.php
In my opinion, I would like to have more independency of setting module for this case. I don't know if this layout style is only for modules or other part of JEM component, in the case, that I want to have a layout style different for module and component.

**Comment by mckillo** [comment]
@Heklaterriol can change the tag to question (it wasn't bug) and for me is closed, all understood. Thanks.
