### ISSUE TITLE
Proposal to change all "_QQ_" is obsolete in INI files

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#117]
I think, that it's old and JL4 doesn't use it. 
I propose to change them to \" in all INI files of JEM (there's 101 time).
If it's confirm, upload commit.

**Comment by mckillo** [comment]
Do you approve it?

**Comment by jojo12** [comment]
I don't understand this function, so I can't decide!

**Comment by mckillo** [comment]
@Heklaterriol have changed it. Thanks.
