### ISSUE TITLE
Categories view breaks when there are featured events and set default layout style

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#118]
JEM 2.3.9 + J4 + Categories view menu = Error, with this error message:: 

Warning: Undefined property: stdClass::$odd in C:\xampp80\htdocs\jl428\components\com_jem\views\categories\tmpl\responsive\default_jem_eventslist.php on line 88

Solution: In \components\com_jem\views\categories\tmpl\responsive\default_jem_eventslist.php 
change this line 88:
```
<li class="jem-event jem-row jem-justify-start jem-odd<?php echo ($row->odd +1) . $this->params->get('pageclass_sfx'); ?>" itemscope="itemscope" itemtype="https://schema.org/Event" <?php if ($this->jemsettings->showdetails == 1 && (!$isSafari)) : echo 'onclick=location.href="'.JRoute::_(JemHelperRoute::getEventRoute($row->slug)).'"'; endif; ?> >
```

to these others:
```
<?php $odd = 0; ?>
          <li class="jem-event jem-row jem-justify-start jem-odd<?php echo ($odd +1) . $this->params->get('pageclass_sfx'); ?>" itemscope="itemscope" itemtype="https://schema.org/Event" <?php if ($this->jemsettings->showdetails == 1 && (!$isSafari)) : echo 'onclick=location.href="'.JRoute::_(JemHelperRoute::getEventRoute($row->slug)).'"'; endif; ?> >
				<?php endif; ?>
```
`$odd `isn't define and the second line, delete row when call $odd. I have taken the line from v.2.3.5 and It works. Check it. Tell me, if upload by commit.

**Comment by jojo12** [comment]
in the 2.3.9 version. I can't reproduce this error!

**Comment by mckillo** [comment]
In J4 admin, go Menus, create a new menu, select a menu type = JEM - Categories. Save.
Go to frontend, clic in new menu and you have the error.

**Comment by jojo12** [comment]
No, I haven't!

**Comment by mckillo** [comment]
You have this view in your web in legacy mode. Change to Layout Style to Default in JEM setting

**Comment by jojo12** [comment]
Can someone else reproduce this? Me not!Am 10.03.2023 12:57 schrieb McKillo ***@***.***>:
This Regioms category don't have any event. You could create a event for this cateory and check it again.

**Comment by jojo12** [comment]
Which browser? I use firefox! In eventlist I remember there is something about safariAm 10.03.2023 12:59 schrieb Jojo Murer ***@***.***>:Can someone else reproduce this? Me not!Am 10.03.2023 12:57 schrieb McKillo ***@***.***>:
This Regioms category don't have any event. You could create a event for this cateory and check it again.

**Comment by mckillo** [comment]
Chrome and Firefox.
@jojo12 Create a event for you category 'Refioms' and should have the error, because it's when there are events.

**Comment by jojo12** [comment]
No such problem! See screenshot!JojoAm 10.03.2023 14:41 schrieb McKillo ***@***.***>:
Chrome and Firefox.
@jojo12 Create a event for you category 'Refioms' and should have the error, because it's when there are events.

**Comment by jojo12** [comment]
Sorry it was in the email
![Screenshot_20230310-151921_Firefox Nightly](https://user-images.githubusercontent.com/2960236/224344986-f72a9cf3-a20c-4a10-bdbe-c811ed3d8865.jpg)

**Comment by jojo12** [comment]
My question did you change something in the default_venues.php inside categories?
I remember some "odds" in the default_venues in eventslist!

**Comment by mckillo** [comment]
One more thing, can you add 'featured' to the "Testevent Regions" event?

**Comment by jojo12** [comment]
it is featured!
you're right, in categories it doesn't show featured, but it is shown in simplelist.
If you want to add this in categories, there must be something inside your changed categories version!
I think, it has to do with the alternate lines of events and for each possibility there must be a version for "featured"

**Comment by mckillo** [comment]
I only have searched $odd into eventslist view of the site (\components\com_jem\views\eventslist\).
I have search these files into 2.3.9 zip file that you tell me and I don't found them. are files of old files?

**Comment by mckillo** [comment]
$odd is used in myattendances, day, search, venuelist and categories view(Site) too.

**Comment by mckillo** [comment]
Commit up 359a9f9dcb6aff01d607becf9dabcb7b4cd3650d

**Comment by jojo12** [comment]
In my different sites I always uninstalled the whole JEM, before installing a new one or installed only jem2.3.9 as fresh.
and I always have "odd" in it
so we live in two different worlds!

I think you start to create new problems, I'm sorry to say that.

**Comment by mckillo** [comment]
I don't know why you think that. I don't understand you but I can try it again. My apologies if I have not expressed myself well on something. I'm not perfect, and my English isn't perfect either. We are in a forum by write messages and that It is a limitation to see and understand what the other is happening to or wants to say (this issue is an example of it).  And yes, I can have a mistake too, if it's so, sorry in advance, I only try to help in this new JEM version for J4 and friendly, please.
 
In this case #118, I only have reported an issue that you have seen and the solution. I don't create any problem, this error is in the code.

When I said 'old file', it could said 'new file' too, I don't know (supposition). I said you that I can't found these files into pkg_jem_v2.3.9.zip file, I don't know where are.
Could you tell me the path of these files (default_eventslist_small.php & default_eventslist.php) in JEM installation or ZIP file?
