### ISSUE TITLE
Small visual improvement of featured events in calendar view and module basic

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#119]
JEM can have featured events, but in calendar view can't see what event is featured. 
I think that it will be good to know what events are featured, because for any reason were created as featured and they could be more visible in the calendar view.

For example, the featured events could have a small border to highlight those events in the table of the month. In the following image, you can see the current result (without any border), and two proposal with 1px and 2px of black border. Do you like it?

![JEM for JL4 - border for event featured in calendar view](https://user-images.githubusercontent.com/2765316/224297833-506e09b7-3d66-4783-95cd-cda9b22ddd23.jpg)

The change in the code is very simple, each events has featured field data and add this code in the div:
`style="border:2px ' . ($row->featured? "black":"white") . ' solid"`

If this improvement is approved, I will upload the code changes by commit.

**Comment by mckillo** [comment]
![JEM for JL4 - border for event featured in calendar view-add code in responsive default php](https://user-images.githubusercontent.com/2765316/224451053-d8048862-c6a0-4ed3-b3ab-1ebda34b022d.jpg)

If you want to try it, it's few code changes in this file site\views\calendar\tmpl\responsive\default.php (JEM project),

**Comment by mckillo** [comment]
This is extensive to modules, for example, JEM Module Basic can show the featured events in bold. So, this type events are visually highlighted

![JEM - Module Basic with features event in bold (Legacy mode)](https://user-images.githubusercontent.com/2765316/224474059-f177ba94-b5c9-4711-92d6-53a41a557370.jpg)

The middle event is marked to be more important.
This view is with layout in Legacy mode (simple).
The code is ready to up, if it is approved.

**Comment by mckillo** [comment]
I'm going to prepare this proposal with setting option in the module.

**Comment by mckillo** [comment]
![JEM - New options in calendar view - features event with border (Legacy and defaut layout style)](https://user-images.githubusercontent.com/2765316/224786096-889cd5c5-f991-456d-972e-2cb29f5877cc.jpg)

@jojo12 Here you are, now the calendar view has 2 options at the end of setting, where the admin can set border and color for the featured events. 

It works as before, both for legacy and default mode (layout style), but now it is more flexible to better visualize the featured events.
Tell me if that places is right. Test it, Uploaded commit 41b6085370d6a4e49bdfdb4270e16850acb9eaa8

**Comment by jojo12** [comment]
tried responsive-calendar . looks good and works fine.

**Comment by mckillo** [comment]
In the CSS can modify width and style border:
```
.borderfeatured {
	border-width: 3px;
	border-style: solid;
}
```

**Comment by mckillo** [comment]
Second part is the update JEM Module Basic (mod_jem). Now, there is a new options in the module setting to active 'highlight style' for featured events.

![JEM for JL4 - New options in jem basic module - features event with highlight style by css (by default bold)](https://user-images.githubusercontent.com/2765316/225050782-0f60fa18-2dd7-4ad4-9f84-968b5f18cc16.jpg)

It works in Default and Legacy layout style. In the css file is the new class 'highlight_featured', by default the style = bold. The admin can change css file to custom this featured style.

Uploaded commit a3639adeb97621d519d5c3179afc90623fe03034
