### ISSUE TITLE
Frontend>new event>error when I don't set a venue

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#120]
When I create/edit an event and I don't choose a venue or no venue (via modal) and try to save, and I add somethin other like featured=yes or something else like "trash"
I get an error:
Speichern fehlgeschlagen. Fehler: Incorrect integer value: '' for column 'locid' at row 1

So I have to choose in the modal an event or "no event".

Proposal, it would be better that it writes automaticly "no venue" if I forget to open the modal and choose "no venue"

**Comment by mckillo** [comment]
This error is similar other issue resolved. In this case locid is empty, and internal validationprocess for this field return null, this locid in the events table is integer not null. locid must be 0 if venue isn't selected. For it, locid must have a default value into events.xml.

Solution: Add `default="0"` in line 145 of \components\com_jem\models\forms\event.xml

Result code with the new line in events.xml [140-146:
```
<field name="locid" type="modal_venue"
			label="COM_JEM_EDITEVENT_FIELD_VENUE"
			description="COM_JEM_EDITEVENT_FIELD_VENUE_DESC"
			size="40"
			required="false"
		    default="0"
		/>
```
After save xml file, you can edit and save without error.

**Comment by jojo12** [comment]
This is excelleNt! Thanks

**Comment by mckillo** [comment]
Upload commit 3d56ffa26d7fa76f192c97f4cede00d55437767b
