### ISSUE TITLE
mod_jem_teaser is too much adapted to mod_jem_banner

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#123]
If I compare the legacy style and the standard style of mod_jem_teaser, in the responsive the eventimages should be smaller (not like now with nearby the same width like mod_jem banner.
Or it should be possible to hide the images, like that you see only the calendar-image and text.

**Comment by mckillo** [comment]
Tell me if add option module to hide/visible image is that you want.

![JEM-Module_Teaser-Show_image_option(default style)](https://user-images.githubusercontent.com/2765316/224548072-f229d902-8c24-4a0a-a620-f8e2009cc9d5.jpg)

Image 400x300 Thumb 275x275 (right side). 
The admin can set this new options to hide image in this module.

This option module 'Show image' can import to other JE modules, do you want to import?
If this improvement is approved, I will upload the code changes by commit.

**Comment by jojo12** [comment]
The show image button is very good!

Do you mean: it would be possible to add the 'Show image' button to other JEM modules too?
For mod_jem surely not, for jem_banner not, for jem_wide perhaps=yes

**Comment by mckillo** [comment]
Uploaded commit b8deb6a0fb9771333676ef7de1b147acfb9be0c1 with the option in JEM Teaser module. @jojo12 check it.
