### ISSUE TITLE
mod_jem_banner event id doesn't work

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#125]
reproduce:
go to mod_jem_banner settings, choose a valid event id to show only this event, save. It shows always the first actual event!

**Comment by jojo12** [comment]
@all: We have to test the possibilities of the modules. The most important was the component, but it seems we have to look to changes in the modules and  plugins too! :-(

**Comment by jojo12** [comment]
mod_jem_teaser has this option too. And it is the same problem, but (for me) here, this is not so bad! But because there is such option, it should work!

**Comment by mckillo** [comment]
I'll try to debug it. Tomorrow I will tell you :-)

**Comment by jojo12** [comment]
;-)

**Comment by jojo12** [comment]
this morning in jem4.datenablage.info it works, even in teaser!

**Comment by mckillo** [comment]
@jojo12 The error in this line, because $tmp is always null :
		`$tmp =  is_array($ids_in) ? $ids_in : (!empty($ids_out) ?  explode(',', $ids_in) : array());`
This line was change for the new version. In the commit ff976c208d8b1ba650200a5b5eacea53524e3d9e is the solution (I think so). Test it.

**Comment by jojo12** [comment]
your commit works, not only with mod_jem_banner, but with mod_jem_teaser too! Thanks a lot!
