### ISSUE TITLE
in branch: mod_jem_teaser show venue-image doesn't work

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#127]
there are two buttons: show event-image and show venue-image. But the show venue-image button doesn't work!
(personally I don't need the venue-image here, but when there is a button he must work!)

**Comment by jojo12** [comment]
I think in 'small fixes'Am 13.03.2023 17:46 schrieb Hekla Terriol ***@***.***>:
in which branch? "JEM-4beta1" or "small-fixes-before-JEM4"

**Comment by mckillo** [comment]
Legacy style shows the venue image. 
Default style shows the both (event, venue).
For these reason, I added two buttons. In Default, Venue doesn't work (there isn't code for it, do you want it?

**Comment by mckillo** [comment]
It's in the "small-fixes-before-JEM4' (see #123 commit b8deb6a0fb9771333676ef7de1b147acfb9be0c1)

**Comment by jojo12** [comment]
In my eyes in mod_jem_teaser the event-image is enough, so you can delete the show venue image button.

**Comment by mckillo** [comment]
I don't know, in the v.2.3.5 you have this option (show venue)....and 2.3.9 has inherited it.
I have used venue in this module. If you apply a filter by category and want you the venue, because sometime it's more important the places that the image event (and the image event is empty).

**Comment by mckillo** [comment]
You have to match the code in the two layouts and add a place to responsive.

**Comment by jojo12** [comment]
ok, but then the venue-image should be visible and in my case it's not!

**Comment by mckillo** [comment]
In responsive layout, there isn't code for it, for that, you can't see any venue image.

**Comment by jojo12** [comment]
ah, now I understand :-)

**Comment by mckillo** [comment]
I suppose that in some version of the past it was implemented for the legacy view.

**Comment by jojo12** [comment]
It's good if you can hide it with a button.

**Comment by mckillo** [comment]
Then, do I add the venue image in default style for this module?

**Comment by jojo12** [comment]
I would say: okay

**Comment by mckillo** [comment]
Tomorrow upload a new commit for it.
These new field have the default value 0, don't show anything, you must set to see images.

**Comment by mckillo** [comment]
"jojo12 Hereyou are.
I have added venue imagen in responsive layout and other small change to improment the responsive view when the module shows 1, 2 or 0 images. Testit please when you have time.

See new commit b931537ba738a6037fd2f616f4f99ba0b461181c  for this update.
