### ISSUE TITLE
Request to remove NUM column in events view (Blackend)

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#129]
The first column in the events view (blackend) is a counter of events in this table for that pagination page. Nothing more.

![JEM-event view backend - delete num column](https://user-images.githubusercontent.com/2765316/224988355-d37c41fd-4154-4de6-8dad-c57cbea5682f.jpg)

In my opinion, this value it isn't useful, it's confuses because the admin/user can be is the event ID. It isn't associated with the event, it changes according to the column sort and filters used.

For example, Joomla and orden extension don't use this counter in their list/table of articles, categories, modules, extension, plugins, ... 
If the cons wins the pros, can it be removed?

**Comment by jojo12** [comment]
I agree, NUM is too much!

**Comment by mckillo** [comment]
Normally in Joomla the ID column is placed at the end, although in the database it is the first.

**Comment by Heklaterriol** [comment]
Yes I agree, NUM is not necessary.

**Comment by mckillo** [comment]
Hekla, sorry, I have upload new commit 72fb471dfc5f3ccf0d2fac77f0f8f6b5652e2ead  to close this, It was delete 2 lines.

**Comment by mckillo** [comment]
One thing less :-)

**Comment by jojo12** [comment]
yes, but you have to delete the column too (not only the header).
If not, the date header is over the num column.

**Comment by mckillo** [comment]
I have deleted 2 lines, the th (header) and td (data). See commit again.

**Comment by mckillo** [comment]
@jojo12 is it all right to close?

**Comment by mckillo** [comment]
Now I have seen it, It already solved in JEM-4beta2
