### ISSUE TITLE
2.3.11: with JEM finder plugin activated new event gives error

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#134]
2.3.11: with JEM finder plugin activated new event gives new error:
"Save failed with the following error: Category must have a title."

but the event is saved, but has no category!

when plugin is deactivated, create event works fine!

**Comment by Heklaterriol** [comment]
could reproduce it once, but not anymore … strange

**Comment by jojo12** [comment]
I don't know if this says something about it. In the logfile everything I found

> 2023-03-17T09:47:12+00:00	CRITICAL 54.36.148.186	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Seite nicht gefunden". Stack trace: #0 [ROOT]/libraries/src/Application/SiteApplication.php(744): Joomla\CMS\Router\Router->parse()
#1 [ROOT]/libraries/src/Application/SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('/home/folktanz/...')
#5 {main}

**Comment by Heklaterriol** [comment]
I have it again.
@mckillo is this something you can fix easily or should I go to the developer with it?

**Comment by mckillo** [comment]
I understand that you have this error "Save failed with the following error: Category must have a title." when you save the new event, is it right?
This error is only call from \administrator\components\com_jem\tables\category.php :139. 
But this error can be shown by other extension, JEM doesn't have to be. To debugger, I have that simulate the error :-(

**Comment by jojo12** [comment]
You can not reproduce?

**Comment by jojo12** [comment]
even when I add a date, the same error!

**Comment by mckillo** [comment]
My error is that smart search joomla doesn't find any event, neither venue..... its function does not work

**Comment by jojo12** [comment]
in cat_events is the combination of event with category. In DB there is the combination for this event. But it seemes some program can't read that for listing of events.

**Comment by jojo12** [comment]
@mckillo: you wrote

> My error is that smart search joomla doesn't find any event, neither venue..... its function does not work

do you mean joomla smart search or JEM smart search?

**Comment by mckillo** [comment]
@jojo12 Check this -->Edit plugins/plg_finder_jem/jem.php and check 217: `echo "fdsfsd";die;` If it exists, delete it.

**Comment by mckillo** [comment]
In the begining, the error was when active JEM smart search (finder). 
If JEM smart search doesn't error (for me), the next step is testing functionality. 
The function is that Joomla smart search finds the events and venues and show in the list item, the JEM events.

**Comment by mckillo** [comment]
And this function doesn't work, Joomla search doens't show any JEM items with the link to event or venue.

**Comment by Heklaterriol** [comment]
I have it again.
@mckillo is this something you could fix or should I go to the developer with it?

**Comment by Heklaterriol** [comment]
And is this the only serious bug which is left and where we possibly need the developer?
He would like to finish the project …

**Comment by jojo12** [comment]
In my eyes this is the one which is left! 
The emergency solution is to deactivate this plugin during entering events in backend or add events in frontend where there is no problem when entering in frontend.
Say thanks to him!

**Comment by jojo12** [comment]
I don't have this at line 217

**Comment by mckillo** [comment]
This plugin would help to Joomla smart search finds the events and venues when the user finds anything in the web (search module) and show in the list item (event and venue).

**Comment by jojo12** [comment]
Thought, this is the function of the normal jem search?

**Comment by mckillo** [comment]
Yes, It's the main function of this type of plugin, but Finder plugins are a complex plugin to migrate.
In webs with a lof of events, this plugin useful for the users when search.
