### ISSUE TITLE
Commits are lost in the last merges

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#135]
![Error to do merge - commits are lost](https://user-images.githubusercontent.com/2765316/225369289-6624b381-4e7d-4547-9a21-d3434d04c722.jpg)

The 2.3.11 version don't have all commit of samll-fixes-before.JEM4.
I have review the mergue and there are error to merge branch (overwritting dev version).
Some examples code commit loosing, if I look at 2.3.11 zip files or merging/fixes/into/beta branch.
:
- \admin\models\forms\event.xml Line 295, 300-302
- \admin\controllers\import.php Line 190, 198
- \admin\models\event.php Line 290
- \admin\sql\install.mysql.utf8.sql 245
- \admin\views\events\tmpl\default.php 104
- \media\css\jem.css 128, 167
- \modules\mod_jem\language\en-GB\en-GB.mod_jem.ini 22,23
- \modules\mod_jem_teaser\language\en-GB\en-GB.mod_jem_teaser.ini36-39,55,56
- \site\helpers\helper.php 1138-1145
- \site\views\mailto\view.html.php 52
and so on.

Please review the current branch, because merging-fixes-into-beta4 doesn't have the final version with the all commits.

**Comment by mckillo** [comment]
@Heklaterriol I have updated more info about it (see above).

**Comment by Heklaterriol** [comment]
Oh, this is bad.
Can we get them back? And how to proceed to do it in a good way?

**Comment by Heklaterriol** [comment]
on the second error on the graphical record, I merged in the wrong direction … :(

**Comment by mckillo** [comment]
As soon as I have a hole today, I start to debug it and see how to solve it. I guess you have to do some revert, reset or another branch. In this case, I don't know what is the best (test it).

**Comment by mckillo** [comment]
I have prepared this branch in local.

In the review, I have seen that the svg files are modificated by change string 2.3.9 to 2.3.10 (I have restored them):
        modified:   media/FontAwesome/fonts/fontawesome-webfont.svg
        modified:   media/FontAwesome/webfonts/fa-brands-400.svg
        modified:   media/FontAwesome/webfonts/fa-regular-400.svg
        modified:   media/FontAwesome/webfonts/fa-solid-900.svg
And this other, updated too:
        modified:   media/css/calendar-responsive.css
        modified:   modules/mod_jem_banner/tmpl/mod_jem_banner.css
        modified:   plugins/plg_finder_jem/jem.php
And I have added the change of commit https://github.com/Heklaterriol/JEM-Project/commit/b02a585f470f0f30c9e066ad6de96141f3b1f792 (to do after new branch, recovered).

When you tell me, I upload it.

**Comment by mckillo** [comment]
But we need to have a branch of reference (stable) to upload new commit.

**Comment by jojo12** [comment]
@mckillo @Heklaterriol: Yes, I know. With this I can't help you and I am very thankful for your work.
Meanwhile I continue testing.
If the package helps you, then please say it.

**Comment by mckillo** [comment]
With your permissions, steps done to have stable beta2 version: 

1. I created branch JEM-4beta2 from master.
2. I merged into JEM-4beta2 from commit https://github.com/Heklaterriol/JEM-Project/commit/9cef9f104266a8e8d5c436b170dba012aef646c9. 
3. I added a new commit to update JEM-4beta2 with others commits upload that in merger operationnot included.
3.1. In this last commit 82feae180efe7a2e595d6ff3b5f084ad519f44cc I have restored the fontawesome files (they have changed by replace string version 2.3.10).

Check it, please, but I think that There's nothing missing (inlcuded all commits before) and it's a beta2 version stable. 
@Heklaterriol @jojo12 Check it. I hope that all these change help you and if it's good, could create a new version 2.3.12.zip :-)

**Comment by Heklaterriol** [comment]
Yes that looks fine for me. Thank you!

**Comment by Heklaterriol** [comment]
And is this the only serious bug which is left and where we possibly need the developer?
He would like to finish the project …
