### ISSUE TITLE
2.3.11: calendar: no featured when categorycolor is set

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#136]
when there is no category color set, then it works perfect,
but when categorycolor is set, then there is no featured

**Comment by mckillo** [comment]
But category color is background, the featured border must be if it's active. one have border and the order none. Are you using different color. By default the border color is#000080 (dark blue). Look at again :-)

![border color active for featured event](https://user-images.githubusercontent.com/2765316/225692063-f72ca849-2c29-4821-969a-6aaade6518a3.jpg)

**Comment by jojo12** [comment]
sorry, It seems I didn't cleared the cache. Works perfect in legacy and standard! Can be closed!
