### ISSUE TITLE
2.3.11: featured events in weekcalendar, categories calendar and venues calendar too?

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#138]
2.3.11: featured events in weekcalendar, categories calendar and venues calendar too?

**Comment by mckillo** [comment]
It's true. Take note. Thank you.

**Comment by mckillo** [comment]
Add highlight of featured events in week, category and venue view. 
Check it. See commit 3643dac60b4bd5d56685895bfd7dcc1172d4e2c1 in Fixes-after-JEM4beta2
