### ISSUE TITLE
2.3.11: myevents and myattendings don't need fa-comment for the title!

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#139]
2.3.11: myevents and myattendings don't need fa-comment for the title!

**Comment by mckillo** [comment]
Could you explain me more details about it?

**Comment by Heklaterriol** [comment]
included in [JEM-4beta2](https://github.com/Heklaterriol/JEM-Project/compare/JEM-4beta2), see https://github.com/Heklaterriol/JEM-Project/commit/9c72cabf757ccbcce0b513fbd999abe7f50f2df0
