### ISSUE TITLE
2.3.11: Layout from export should be better

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#140]
it's a proposal post from wesselsjan: 
This suggestion concerns the backend of JEM at the page Export Data where we can choose the categories to export. The layout could be better with Category at the left-top and Select all categories / Unselect all categories at the right-top next to the category list.

The height of the Export File button should be a little higher.

![jem-export_2023-03-16](https://user-images.githubusercontent.com/2960236/225733476-8a17efc8-83d2-4107-b17c-a00d08d55a76.jpg)

**Comment by mckillo** [comment]
![JEM4 - Draft design export  view - version 1](https://user-images.githubusercontent.com/2765316/226274783-4a775a65-1252-4f30-ac40-77d4ee323af2.jpg)

This is simple draft of redesign for export view. Structured in 3 blocks main (div) with flex display.
What is your opinion?

**Comment by jojo12** [comment]
Looks good. I agree

**Comment by mckillo** [comment]
![JEM4 - redesign export page (backend) - draft1](https://user-images.githubusercontent.com/2765316/226494939-07aab058-ba2a-4510-8785-5bf57f06c4cd.jpg)

Here you are new version of the redesign export page in backend. 
See commit 5ddcdaa66fc5c7dc06e3cacd7922c260d33c08ed
