### ISSUE TITLE
installation of higher version --> Internal Server Error

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#141]
when I try to install a new version of JEM, e.g 2.3.10 over 2.3.9 I get an "Internal Server Error" message from Joomla.

Then I tried to install package by package in this order

1. com_jem.zip --> OK

mod_jem.zip --> Internal Server Error
mod_jem_wide.zip --> Internal Server Error
mod_jem_cal.zip --> Internal Server Error
mod_jem_calajax.zip --> Internal Server Error
mod_jem_teaser.zip --> Internal Server Error
mod_jem_banner.zip --> Internal Server Error
mod_jem_jubilee.zip --> Internal Server Error

plg_content_jem.zip --> OK
plg_content_jemlistevents.zip --> OK
plg_search_jem.zip --> OK
plg_finder_jem.zip --> OK
plg_jem_comments.zip --> OK
plg_jem_mailer.zip --> OK

even with error reporting on maximum I do not get any information.

When trying to install mod_jem_wide.zip I get the following log entry:

```
#Fields: datetime	priority clientip	category	message
2023-03-17T16:58:09+00:00	CRITICAL 84.134.202.142	error	Uncaught Throwable of type Error thrown with message "Class "Factory" not found". Stack trace:
#0 [ROOT][TMP]/install_64149c21c547a/mod_jem_wide/script.php(34): mod_jem_wideInstallerScript->getParam('version')
#1 [internal function]: mod_jem_wideInstallerScript->preflight('update', Object(Joomla\CMS\Installer\Adapter\ModuleAdapter))
#2 [ROOT]/libraries/src/Installer/LegacyInstallerScript.php(151): call_user_func_array(Array, Array)
#3 [ROOT]/libraries/src/Installer/LegacyInstallerScript.php(171): Joomla\CMS\Installer\LegacyInstallerScript->__call('preflight', Array)
#4 [ROOT]/libraries/src/Installer/LegacyInstallerScript.php(91): Joomla\CMS\Installer\LegacyInstallerScript->callOnScript('preflight', Array)
#5 [ROOT]/libraries/src/Installer/InstallerAdapter.php(1054): Joomla\CMS\Installer\LegacyInstallerScript->preflight('update', Object(Joomla\CMS\Installer\Adapter\ModuleAdapter))
#6 [ROOT]/libraries/src/Installer/InstallerAdapter.php(713): Joomla\CMS\Installer\InstallerAdapter->triggerManifestScript('preflight')
#7 [ROOT]/libraries/src/Installer/Installer.php(644): Joomla\CMS\Installer\InstallerAdapter->install()
#8 [ROOT]/administrator/components/com_installer/src/Model/InstallModel.php(195): Joomla\CMS\Installer\Installer->install('/www/htdocs/w01...')
#9 [ROOT]/administrator/components/com_installer/src/Controller/InstallController.php(52): Joomla\Component\Installer\Administrator\Model\InstallModel->install()
#10 [ROOT]/administrator/components/com_installer/src/Controller/InstallController.php(100): Joomla\Component\Installer\Administrator\Controller\InstallController->install()
#11 [ROOT]/libraries/src/MVC/Controller/BaseController.php(672): Joomla\Component\Installer\Administrator\Controller\InstallController->ajax_upload()
#12 [ROOT]/libraries/src/Dispatcher/ComponentDispatcher.php(143): Joomla\CMS\MVC\Controller\BaseController->execute('ajax_upload')
#13 [ROOT]/libraries/src/Component/ComponentHelper.php(355): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
#14 [ROOT]/libraries/src/Application/AdministratorApplication.php(143): Joomla\CMS\Component\ComponentHelper::renderComponent('com_installer')
#15 [ROOT]/libraries/src/Application/AdministratorApplication.php(186): Joomla\CMS\Application\AdministratorApplication->dispatch()
#16 [ROOT]/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\AdministratorApplication->doExecute()
#17 [ROOT]/administrator/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#18 [ROOT]/administrator/index.php(32): require_once('/www/htdocs/w01...')
#19 {main}
```

Any ideas?

**Comment by Heklaterriol** [comment]
All modules produce the exact same call stack (except the name of the module)

**Comment by mckillo** [comment]
When I try to update from 2.3.9 to 2.3.10,I have these error messages in JL 4.2.9:

![error to update from 2 3 9 to 2 3 10](https://user-images.githubusercontent.com/2765316/225993665-5d1ebbdb-57b4-4dfb-aa14-aa5088729784.jpg)

I think that we review the update process for J4 and the first error is the ZIP files have the same version 4.0.0

**Comment by Heklaterriol** [comment]
This is because in the previous test versions in the com_jem package there was the version number 4. 
You can check the version in the Joomla Extension Manager. 

You can change it in the DB table under
\> `#_extensions` > `com_jem` > `manifest_cache`.
There you find the entry `"version":"4"` (or similar) set it to `"version":"2.3.10"`

Thereafter you can update to higher versions.

**Comment by mckillo** [comment]
In my installation, version =4.0.0 change to 2.3.10, and I have other error:
![error to update from 2 3 9 to 2 3 10 with com_jem_db_manifiest_version_2 3 10](https://user-images.githubusercontent.com/2765316/226095799-b9ab0211-0fed-4cd2-858b-acd0b6b19505.jpg)

I think that the error is ZIP package in pkg_jem_v2.3.10.zip\pkg_jem_v2.3.10\packages\com_jem\script.php (function preflight when it has to update version). I'll try to debug but this weekend I'm busy.

**Comment by mckillo** [comment]
@Heklaterriol Check it the commit 9c010b18bf5977cee1d730be6200254fc7c0a8ff, solved the error module.
Tomorrow I will finish the script.php update of com_jem (this file is old and give me errors too)

**Comment by Heklaterriol** [comment]
commit 9c010b18bf5977cee1d730be6200254fc7c0a8ff works fine, thank you!

**Comment by Heklaterriol** [comment]
I was also necessary to change the version to a higher number.
I put it to 2.3.12, checked it and pushed it to [JEM-4beta2](https://github.com/Heklaterriol/JEM-Project/tree/JEM-4beta2)
