### ISSUE TITLE
2.3.11: Strange comportment 2: when there is a category calendar

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#143]
When I have a category calendar and I click in categories on the category link of a category, I normally should reach the category ciew of this category. But I only reach the category calendar of the clicked category (even when I don't have a menue "calendar for this category"!)

**Comment by mckillo** [comment]
As in the previous case, I don't see the issue, could you indicate more details or capture view?

**Comment by jojo12** [comment]
same like in venue calendar:
capture isn't possible, I can't capture a switch!
To reproduce (in jem4test.joomla.com)
I created a menue item: "Kategoriekalender" for PC Erlinsbach. This works!
Then I go to "Agenda"= Simplelist and click on the link of a category. 
Without "category calendar" I get the category view of the linked category
But now I get a category calendar of the clicked category.

**Comment by mckillo** [comment]
In this case, in a issue of Joomla but It depends of the menu active created.
See explicaion in #142 (it's the same, change venues for cateogies)

Solution: Create a unpublish menu of type: JEM categories and you'll have the right link for each category in Agenda page.

**Comment by jojo12** [comment]
Same here like in #142. works perfekt.
Good to know!
