### ISSUE TITLE
Fix stabilized style of categories buttons for calendar views

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#145]
![JEM4 - Stabilizes style of categories buttom in views](https://user-images.githubusercontent.com/2765316/226269014-a0554425-a1bb-49fc-974f-181a3f0498ad.jpg)

Fix small change into css files, avoiding overlaps and loss of style.
Upload commit 8a95d09e910ae8b48a6d39ea78ab09ad8aec9241

**Comment by Heklaterriol** [comment]
included in [JEM-4beta2](https://github.com/Heklaterriol/JEM-Project/compare/JEM-4beta2), see https://github.com/Heklaterriol/JEM-Project/commit/722c14cc2a619c78275cbd283be4ea6817184337
