### ISSUE TITLE
2.3.12: fresh install: why in the jem settings is only image height?

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#148]
in the JEM settings this problem is back: I need both settings (image height and image width). We had this problem earlier, is it back? For me this is a bug!

**Comment by mckillo** [comment]
@jojo12 the 2.3.12 zip don't include commits Fixes-after-JEM4beta2 branch.
10 minutes ago, I have merged this branch into JEM-4beta2 (with the permission of Hekla), now it's update,but zip no.
I don't know what the number issue was before to review. Do you remember it?

![JEM4 -setting page with height (backend)](https://user-images.githubusercontent.com/2765316/227049817-a447edbc-9936-4ef0-b13e-4d59cdc845ab.jpg)

I want to understand ir, you said, that need to have the width max field for image. is it right? and the previous version it had.

**Comment by Heklaterriol** [comment]
it is fixed
