### ISSUE TITLE
Important Info: JComment Joomla 4 works fine with JEM - don't need the plugin!

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#149]
in jem4test.joomla.com I got a demo version of JComment. I tested and it works fine. You can have a look too

**Comment by Heklaterriol** [comment]
As I have never used the JComments Plugin I have to ask a potentially stupid question:
What do you mean by "don't need the plugin"? that the JEM JComments Plugin is not needed anymore, beacause JComments works with JEM without it the plugin?

**Comment by jojo12** [comment]
Earlier this was a free component. And I tried it, but used it not very long! Now I wanted to try and got a trial. It is now made, that the component can reach every component without any plugin! The free trial is on jem4test.joomla.com

**Comment by Heklaterriol** [comment]
Ok. So then let's remove the JComments Plugin.
I think it is good to mention on the JEM web page, that JComments now works without plugin.

**Comment by jojo12** [comment]
I agree!
