### ISSUE TITLE
Add precise instructions for the users to update from JEM 2.3.5 to 4.0

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#151]
Where?
- on the website
- in the package
- ...

**Comment by jojo12** [comment]
I didn't test but I think you can't update from 2.3.5 to 2.3.12 on Joomla! 3. 
Or does 2.3.12 works under joomla3?
Until now I always installed under Jooml! 4.

**Comment by Heklaterriol** [comment]
> but I think you can't update from 2.3.5 to 2.3.14 on Joomla! 3. 

That is correct – 2.3.5 is the last working relase for J3.
I suggested a information release for J3, see #178

**Comment by Heklaterriol** [comment]
Does anybody feel like making and writing down a step by walk-through
- from JEM 2.3.5 / J3 / php 7.4 or 8
- to JEM 4 / J4 / php 8

and hopefully catch all the traps ?

The other may then test the process description.

**Comment by Heklaterriol** [comment]
Is Jojos description sufficient?

**How to update to JEM 4 for Joomla 4 and PHP 8**

- In Joomla! 3 Update to Joomla! 3.10.11
- Update to php 8.0+
- Update to JEM 2.3.5
- Export via ftp the folder media/com_jem/attachments with subfolders and attachments
- Export via ftp the folder images/jem with subfolders and images
- If you want the same JEM settings, you have to write it down.
- Export via JEM export all the events (choose categorycolumn=yes, select all categories und a startdate and enddate with all events inside)
- Export categories, venues and cat_events
- For safety reasons it would be better not to delete your old Joomla3! Better to install Joomla!4 parallele to old Joomla! 3
- Install Joomla! 4
- Install JEM 4
- Go to JEM settings and set them like before or like you want
- Import via ftp the folder images/jem with subfolders and images
- Import via ftp the folder media/attachments with subfolders and attachments
- Import via JEM import all the venues, categories, events and cat_events (exported csv files)
- You have to adapt the user IDs (best in DB) - your admin ID in Joomla!4 will not be the same.
- Finish

**Comment by Heklaterriol** [comment]
or these instructions:

- Update to JEM 2.3.6
- Make a backup!
- Disable the JEM extensions, all jem plugins, all JEM modules
- (During upgrade process, it suggested to switch to Joomla3 default template "Protostar")
- To prepare the update from Joomla3 to Joomla4, go to _Components_ > _Joomla! Updates_, choose _Options_ and in _Update Channel_ choose _Joomla Next_.
Save.
Then you get the informations about which other components are not ready. Perhaps I have to disable/uninstall other components/modules/plugins not prepared for Joomla4)
- Then upgrade from Joomla3 to Joomla4.
- Install JEM 4
- Before switching to the frontend, change the positions of the JEM-modules and the main menue, to the positions of your new Joomla4 template (e.g. the Joomla4 default template "cassiopeia"!
- Enable all JEM 4 (component, modules, plugins)
- Adapt the JEM settings (there are changes: e.g. datetime format)
- Check everythink if it works!

Finish :-)

**Comment by jojo12** [comment]
👍
