### ISSUE TITLE
To review: Old Demo plugin

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#155]
For the Demosite there is an old demo plugin which resets all datas after a while. It seems to work, but it would be good to review it for changes! Where should I post it?
@mckillo ?

**Comment by mckillo** [comment]
@jojo12 I don't know this plugin, but I guess that it's a timer to restore table by default.
If it's there is review of table because change, see last commit 9bd65eb8743be3f6b90ad88ff747915dea63ecf2

**Comment by jojo12** [comment]
[plg_jem_demo-2.2.1-dev007.zip](https://github.com/Heklaterriol/JEM-Project/files/11069061/plg_jem_demo-2.2.1-dev007.zip)

**Comment by jojo12** [comment]
it works, but it is good to review

**Comment by jojo12** [comment]
meanwhile, I exchanged all "0000-00-00 00:00:00" with NULL. It works like that.

**Comment by jojo12** [comment]
And in the sql the creator is 610. It's better to exchange this with the mainuser ID of the site!

**Comment by Heklaterriol** [comment]
Do you want to create a repository and update and maintain it properly?
Would be good, I think!

**Comment by jojo12** [comment]
It is only used for demo.joomlaeventmanager.net.
I fixed its, it is in use, can be closed!
