### ISSUE TITLE
In migrate process, check and update JEM (tables and data), new SQL script

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#156]
Migrate from J3 + JEM 2.3.5 (uninstall) to J4 + JEM 2.3.12 (install) on same server.
Step to simulate:
- Uninstall JEM 2.3.5 (there are JEM tables with data).
- Migrate Joomla 3 to 4.2 (min version for new JEM).
- Install JEM 2.3.12

In this last step, there aren't process of SQL script to update de tables and data (this isn't import).

In the morning, I have updated a new commit to FIxes-after-JEM4beta2 with change int install sql script, I try to have one with the update table and data if it's detected JEM table with data.

**Comment by jojo12** [comment]
Don't forget, if there are attachments and images!

**Comment by mckillo** [comment]
News scripts to install com_jem, install mysql and sample data. See commit 1b8ad93581014b55ee785c313d59e3a7e6d80454.
I have data migration processing pending on the same server when the new JEM version is installed and another part of the script for processing new updates.

**Comment by jojo12** [comment]
see #180: You don't need to uninstall JEM 2.3.5 to migrate. It is enough to disable all JEM befor upgrading to Joomla! 4 and after to install JEM4 (2.3.14) over JEM 2.3.5. And then enable all JEM!

**Comment by jojo12** [comment]
Do you never sleep?

**Comment by mckillo** [comment]
Some time :-)

**Comment by mckillo** [comment]
I have upload the second phase of install and update script. 
Check it, it's important to testing (new and update install). 
I'm testing for migration from J3+JEM(disable) to J$+JEM(install new version).
See commit a23cb5039b012ec3c0a168e679a62c97c3a945a5

**Comment by mckillo** [comment]
Second update scripts. 
New ZIP fail with scripts updated. https://github.com/mckillo/JEM-Project/blob/JEM-4beta2/pkg_jem_v2.3.15_with%20script_updated.zip
Better test this new zip. Thanks

See e5ebd9e1688fc26a6850416dddc0a0317327de90
