### ISSUE TITLE
Changes in status (archive)

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#16]
#1309
Backend>Archived event >edit (changing date):
Call to undefined method Joomla\Component\Finder\Administrator\Indexer\Helper::getContentPath()
-->but saves!

Backend>Archived event >edit (changing status): Call to undefined method
Joomla\Component\Finder\Administrator\Indexer\Helper::getContentPath() but saves!

**Comment by Heklaterriol** [comment]
@jojo12 : can you check if it still exists. The coder asked for it. On my site it is fixed.
