### ISSUE TITLE
Errors in 2.3.13! don't publish!

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#161]
Unmatched ')'                  
                            

Call stack
--
# | Function | Location
1 | () | JROOT/modules/mod_jem_teaser/mod_jem_teaser.php:16
2 | Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:55
3 | Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch() | JROOT/libraries/src/Helper/ModuleHelper.php:281
4 | Joomla\CMS\Helper\ModuleHelper::renderRawModule() | JROOT/libraries/src/Helper/ModuleHelper.php:161
5 | Joomla\CMS\Helper\ModuleHelper::renderModule() | JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:99
6 | Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render() | JROOT/libraries/src/Document/HtmlDocument.php:667
7 | Joomla\CMS\Document\HtmlDocument->countModules() | JROOT/templates/cassiopeia/index.php:99
8 | require() | JROOT/libraries/src/Document/HtmlDocument.php:736
9 | Joomla\CMS\Document\HtmlDocument->_loadTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:791
10 | Joomla\CMS\Document\HtmlDocument->_fetchTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:608
11 | Joomla\CMS\Document\HtmlDocument->parse() | JROOT/libraries/src/Application/CMSApplication.php:1004
12 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:722
13 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:299
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
15 | require_once() | JROOT/index.php:32

</div>
</body>
</html>

**Comment by jojo12** [comment]
also: in simplelist:
Joomla\CMS\Filesystem\Folder::folders: Path is not a folder. Path: [ROOT]/media/com_jem/attachments

**Comment by jojo12** [comment]
also in venueslist:
0 Undefined constant "php" 

all this errors were just repared!

**Comment by mckillo** [comment]
Yes, it was solved 3 days ago in commit 75de0a51850090e2888b75ce29155b083cdbf626

**Comment by Heklaterriol** [comment]
This is strange.
I had all the commits included – this is not the first time, that there is something wrong, when I try to build an installtion package …  :-(

**Comment by mckillo** [comment]
@Heklaterriol I'm going to upload commits to Fixes-after-JEM4beta2 branch, so you can test it before add to JEM-4beta2 branch.

**Comment by mckillo** [comment]
This is the reason, working branch and beta zip branch. 
If you want, I can merge from this branch to JEM-4beta2.

**Comment by jojo12** [comment]
I wanted to write you, for you have less work!

**Comment by Heklaterriol** [comment]
Thank you McKillo.
I suggest, that you manage the branchend and commits instead of me – it seems safer.
Do you agree?
I would the create a "Hekla-branch" to offer my commits. Or is there a besster solution?

**Comment by mckillo** [comment]
@Heklaterriol Merge branch is done. JEM-4beta2 is updated with all commits.
You can create a new release 2.3.13 or 14.
I help you of merge and commits, no problem, but If you need to do as before, no problem too.
