### ISSUE TITLE
wrong php in views/venueslist/tmpl/default_venues.php

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#162]
I tried to correct it with commits, but persists always!

**Comment by mckillo** [comment]
Any data of error?

**Comment by jojo12** [comment]
There are 3 notices with <?php 
Kopfzeile
Show cities
Show venues

**Comment by mckillo** [comment]
I don't see it in my local site, What release/code? Send me capture o url?

**Comment by jojo12** [comment]
from your package. 2.3.13:
![bugs](https://user-images.githubusercontent.com/2960236/227761461-51887fc5-1321-4c7d-957f-cbd78b5ba9a8.png)

**Comment by mckillo** [comment]
@jojo12 Here you are. See commit db828574482daff913ae2f0b9f896ef0a65a2a21
