### ISSUE TITLE
Error: Frontend copy event with JEM smart search enabled

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#163]
When JEM smart search is enabled and I copy an event in frontend, I only change the date and try to save, then I get the error 

> Save failed with the following error: Category must have a title.

the copied event is saved but with no category!

Whem JEM smart search is disabled, and I do the sam thing, all works correct.

It looks the same like earlier in backend

**Comment by mckillo** [comment]
I can't simulate this issue, for me works, with JEM smart search active.

**Comment by mckillo** [comment]
I think that this issue is same that #134 and this error of title category issolved by commit 5e797637d6e547aab6fb6e37061271d6978f1f9d

**Comment by jojo12** [comment]
yes you're right. With this commit it works!
