### ISSUE TITLE
Variables COM_JEM_PRE- and POSTFLIGHT_UNINSTALL_TEXT

### ISSUE THREAD

**Issue by jobrusche** [Heklaterriol/JEM-Project#164]
When uninstalling JEM beta4 component 2 variables are displayed:

COM_JEM_PREFLIGHT_UNINSTALL_TEXT and COM_JEM_POSTFLIGHT_UNINSTALL_TEXT

I expected to see some text there instead of the variable names.

[JEMpre-pos-uninstall.pdf](https://github.com/Heklaterriol/JEM-Project/files/11071143/JEMpre-pos-uninstall.pdf)

**Comment by mckillo** [comment]
Include to next beta release (See commit 9e94a2d325954b174cf67bb4b4451dc10b47d807)

**Comment by Heklaterriol** [comment]
We should then add a value for the language string …
