### ISSUE TITLE
backend>events: pagination is much too far right

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#169]
The pagination is too far on the right --> this is not userfriendly (I just tought, there's none!

**Comment by jojo12** [comment]
venues, and categories too, but they have less columns!

**Comment by mckillo** [comment]
Now in events view (backend), the block of pagination is centered, and the number item per page move to right. @jojo12 is it right?

![JEM4 - pagination block centered in events view (backend)](https://user-images.githubusercontent.com/2765316/228063615-add866e0-e432-4cfd-95be-e3747b0fc6e8.jpg)

See commit fdb9a4418579389b35931a4b3bd97466bc6a0dbf

**Comment by mckillo** [comment]
I have updated other views (venues, categories, attendees and groups).
See commit 240b2e5ad324fd18ee693d7f394f6a37e3103453
