### ISSUE TITLE
corrrect code for date format?

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#176]
I found in `site/classes/output.class.php` in line 1475-1476 the following code:

```
$formatD = 'Y-m-d';
$formatT = '%H:%M';
```

is this correct? As this is the old formatting …

**Comment by mckillo** [comment]
This is an inheritance possibly from eventlist. In this same file, the code has a formattime (line 1245) and use that format, 
I have to investigate and then clean all references with % in date and time.

**Comment by mckillo** [comment]
This format % was add to code on Nov 25, 2013.... I have to review it and change all of them.

**Comment by mckillo** [comment]
I update the datetime format in XML and some variable. See commit 7f2ec2d8207eb705942757bc1dca56b5b86dc6e0
I have tested new and update events, new and update venues, it works.
MySQL script was already updated with this format and for example, created field is starting with current datetime directly.
