### ISSUE TITLE
Waitinglist

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#18]
#1311
There seems to be a problem with the waitinglist.
The icons for "on the waitinglist" are not shown.

**Comment by Heklaterriol** [comment]
Where exactly should icons for "on the waitinglist" be displayed and are not?

**Comment by jojo12** [comment]
You're right: it seems I made a mistake, sorry! Can be closed

**Comment by jojo12** [comment]
see attendees in JEM 3
https://jem3.datenablage.info/jem-simplelist/event/4-rock-punk.html
