### ISSUE TITLE
Update to JEM4 in Joomla!4

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#180]
(Preparation: You have to update via Joomla!3.10.11 and JEM2.3.6. JEM2.3.5+ works with php 8.0+.)

**Comment by jojo12** [comment]
I tried much easier: from an installed Joomla!3.10.11 with JEM 2.3.5!
I make a backup!!!
I disable all JEM
(Perhaps I have to disable/uninstall other components/modules/plugins not prepared for Joomla!4)
I upgrade from Joomla!3 to Joomla!4.
I install JEM 4 (2.3.14+)
I enable all JEM 4 (component, modules, plugins)
control->works! Finish :-)

**Comment by jojo12** [comment]
After Method 2 I tried to copy an event: I get an error:

> Save failed with the following error: Field 'modified' doesn't have a default value

My question: Has this to do with the change from 0000-00-00 to NULL?

**Comment by Heklaterriol** [comment]
> > Save failed with the following error: Field 'modified' doesn't have a default value
> (copy an event or a category, there are no such problems)
> My question: Has this to do with the change from 0000-00-00 to NULL?

Maybe we need to write an sql update routine to update these fields.

**Comment by jojo12** [comment]
I checked the new sql script #156! But the error persists.

**Comment by mckillo** [comment]
I'm with the mysql script, because if you migrate Joomla with the old table from JEM 2.3.5 then you have this error, because you tables waren't migrated. Your datetiem field ware with '0000-00-00 ...' format and  these field can't be null. All that generate error.

In the mysql script, there are detect all table with datetiem field and apply the change (structure and old date). It's second part of issue #156(not finished)

**Comment by jojo12** [comment]
Backend>venue>save as new 
Problem persists!

**Comment by jojo12** [comment]
works fine!!!

**Comment by jojo12** [comment]
back again, after six hours of not doing, I open JEM again and I get following problem:
Warning
There are tables not up to date!
I will now try to use db button to repare db

**Comment by mckillo** [comment]
Solved. See commit 00b5357d57c412b6746f8de5d97f7c427ebb8337
After install last version 2.3.15 (yesterday), the attributes COLUMN aren't required, when Joomla check the update mysql, detect COLUMN as error in tables DB.

**Comment by jojo12** [comment]
I tested! works fine! super.
