### ISSUE TITLE
Class "Factory" not found from "email to a friend" (beta2 2.3.12)

### ISSUE THREAD

**Issue by jobrusche** [Heklaterriol/JEM-Project#182]
View event -> Click on icon email-to-a-friend -> stackdump in pop-up window  : 0-Class "Factory" not found
Joomla 4.2.9 - PHP 8.0.32 + PHP 8.0.28 (2 websites)

[Class Factory not found.txt](https://github.com/Heklaterriol/JEM-Project/files/11105380/Class.Factory.not.found.txt)

**Comment by jobrusche** [comment]
![image](https://user-images.githubusercontent.com/117929258/228665294-593857fa-d7c9-4c5c-b072-9faf61488975.png)

**Comment by Heklaterriol** [comment]
fixed and also some other issues with "mail to a fried"

**Comment by jobrusche** [comment]
Installed beta2   2.3.15  -> fixed, no stackdump
