### ISSUE TITLE
Backend - Edit Venue : all top buttons inactive (beta2  2.3.12)

### ISSUE THREAD

**Issue by jobrusche** [Heklaterriol/JEM-Project#183]
Edit existing venue
All buttons  on top of page  Save, Save & close, Save & new, Save as copy and Close are inactive
Tested on 3 sites

**Comment by Heklaterriol** [comment]
Thank you for contributing.
Please use version 2.3.14 to test.
See https://github.com/Heklaterriol/JEM-Project/tree/JEM-4beta2

**Comment by Heklaterriol** [comment]
frontend or backend?

**Comment by jobrusche** [comment]
Now installed 2.3.15 --- Same problem

**Comment by jobrusche** [comment]
The package I installed is 7.611 kB large, the package you refer to above, has 3.897 kB, so which 
one is "whole" ?

Anyway after a night, the cache was cleared and the problem is gone with the 2.3.15, I installed.

**Comment by Heklaterriol** [comment]
The the 2.3.15 package was released **after** you wrote 
> Now installed 2.3.15 --- Same problem

But the files were already pushed to GitHub.

> The package I installed is 7.611 kB large, the package you refer to above, has 3.897 kB, so which one is "whole" ?

locally in my computer and also according to GitHub it is 3.81 MB  …

But anyway – it works again.
And these inactive buttons in joomla is a general though seldom phenomenon
