### ISSUE TITLE
Error in Backend>Venue>copy venue

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#186]
When I try to copy an existing venue in backend, I get the error:
> Save failed with the following error: Field 'modified' doesn't have a default value

(This is general and not only after updating)

**Comment by mckillo** [comment]
@jojo12  If you have time, can test it  with the last commit upload in #156 (update scripts)

**Comment by jojo12** [comment]
The problem persists!
after the descripted way to Joomla! 4, the problem persists with the same notification:
danger
Save failed with the following error: Field 'modified' doesn't have a default value

**Comment by jojo12** [comment]
in venues all venues have the modified field empty, except the tried one, which has 2023-04-01
in DB all venues have 0000-00-00 00:00:00, except the actual one which has 2023-04-01 12:25:05.

in events all events have the modified field empty, except the tried one, which has 2023-04-01
in DB all events have 0000-00-00 00:00:00, except the actual one which has 2023-04-01 12:25:05.

**Comment by mckillo** [comment]
Why do you have venues with 0000-00-00 00:00:00 in modified field? They must convert to null during the import (if they are imported) or they are converted to null during of update/install process 2.3.15 if they are into venue table (DB),
Can you publish your venue table structure to check? modified field must null default null, is it right? If it's yes, then the change this table is right, then the error is in the migration data.

**Comment by mckillo** [comment]
Have you installed with 2.3.15 updated from my commit? This version has script to migrate data (datetime to null).

**Comment by jojo12** [comment]
I don't understand this.
I installed your version in the way I described! Then I looked into the modified fields and the db.

**Comment by mckillo** [comment]
I have managed to simulate the error and I have been able to debug it.

**Comment by jojo12** [comment]
👍

**Comment by mckillo** [comment]
@jojo12 Test it this new ZIP file:pkg_jem_v2.3.15_with script_updated.zip in commit: fe3855eaecec47430a4abb0883e877741ec9a3bd

If It works, I'll upload change to Fixes-after-JEM4beta2 branch.

**Comment by mckillo** [comment]
Envioroment and migration process:
1. Install Joomla 3.10.11
2. Install JEM 2.3.5
3. JEM - Load sample data.
4. Disable all JEM plugin (don't uninstall)
5. Migrate Joomla 3.10.11 to Joomla 4.2.9
6. Install JEM 2.3.15 (new zip file).

Now, JEM is installing without error, and mysql schema s migrating and all datetime fields with '0000- ...' change to null.
All data is working. I think, that it's better process to migrate JEM without loosing any data.

**Comment by jojo12** [comment]
works, no errors 12:17 all ok!

**Comment by jojo12** [comment]
Congrats!

**Comment by jojo12** [comment]
can be closed!

**Comment by mckillo** [comment]
This issue was fixed, isn't it so?

**Comment by jojo12** [comment]
Its fixed
