### ISSUE TITLE
JEM 2.3.5 (2.3.6) Problem  after clean install!

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#188]
When I try to install a clean JEM 2.3.5  and then trying to save JEM settings) I get the error (we know #60)
> danger
Save failed with the following error: Field 'modified' doesn't have a default value

If we prepare a new version JEM 2.3.6, we should correct this!

**Comment by jojo12** [comment]
Attempt to assign property "css_backend_usecustom" on string	C:\xampp\htdocs\mysite.ch\libraries\vendor\joomla\registry\src\Registry.php:814											
							

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\registry\src\Registry.php:814
2 | Joomla\Registry\Registry->bindData() | JROOT\libraries\vendor\joomla\registry\src\Registry.php:809
3 | Joomla\Registry\Registry->bindData() | JROOT\libraries\vendor\joomla\registry\src\Registry.php:335
4 | Joomla\Registry\Registry->loadObject() | JROOT\components\com_jem\classes\config.class.php:150
5 | JemConfig->bind() | JROOT\administrator\components\com_jem\models\settings.php:95
6 | JemModelSettings->store() | JROOT\administrator\components\com_jem\controllers\settings.php:121
7 | JemControllerSettings->save() | JROOT\libraries\src\MVC\Controller\BaseController.php:702
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_jem\jem.php:48
9 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:402
10 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:377
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:101
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:225
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\index.php:51

**Comment by mckillo** [comment]
I don't know this version 2.3.6, Is it for Joomla 3? But it it's so, I don't think it's necessary
The last beta version is 2.3.15 for Joomla , and with this version, you can migrate from 2.3.5 in J3 to 2.3.15 in J4.
And I suppose that the final release will be 3.0.0 or 4.0.0 (If you want to pair with Joomla 4)

**Comment by mckillo** [comment]
And The bug has been fixed by this morning's commit with new scripts. See #156

**Comment by mckillo** [comment]
Sorry I don't see the other branch in Github.
It would be good to know what is the final version (3.0? 4.0?), because there are changed the version number into install and mysql scripts.

**Comment by jojo12** [comment]
My situation was the following. For testing purposes, I installed a clean JEM 2.3.5 oon a clean joomla 3.10.11. Then I had always this problem that I wasn't able to prepare and save some settings, before trying to update to Joomla!4. 
If we give a last version to Joomla! 3 we should correct this error in the install file.

**Comment by mckillo** [comment]
I think that you need apply the solution #60 but with the css setup for JEM 2.3.5, do you try it ? In the code https://github.com/Heklaterriol/JEM-Project/blob/2.3.6-preupdate-release/admin/sql/install.mysql.utf8.sql doesn't, the line297 is css field start with '' (empty). There are any css configuratioin.

**Comment by Heklaterriol** [comment]
does this persist or can we close it?

**Comment by jojo12** [comment]
I can't test it. Is this line now integrated?

**Comment by mckillo** [comment]
If you mean a merge this branch to new version, this línea branch can't integrate into JEM-4beta2 because old code for J2&J3 were deleted.

**Comment by jojo12** [comment]
Forget it

**Comment by Heklaterriol** [comment]
This branch is a potential pre-update release for J3.
See  #178

**Comment by Heklaterriol** [comment]
It this a real issue or can we close it?

**Comment by jojo12** [comment]
Because I fear that Joomla! 3 will live much longer than they think, there will be users which want to start with the best JEM for Joomla! 3. If so, they will have the same problem, we had starting new with JEM for Joomla! 4. So I prefer to correct the install.sql

**Comment by mckillo** [comment]
The solution is https://github.com/Heklaterriol/JEM-Project/issues/188#issuecomment-1495061678 but for JEM for J3

**Comment by jojo12** [comment]
right!

**Comment by mckillo** [comment]
@jojo12 Check it please, and if it's good, close it (one less).

**Comment by jojo12** [comment]
works thanks
