### ISSUE TITLE
Registration as guest not possible (only inside the community)

### ISSUE THREAD

**Issue by dermaxem** [Heklaterriol/JEM-Project#190]
even if i set "Registration" to "Everybody" it is not possible for a guest to register to an Event. Theres still a message "U have to login...".
Registraion shoud be possible as guest and then need a E-Mail-Field to fill in

**Comment by jojo12** [comment]
This is wanted like this. If you register in Joomla, you have to to give only your name and your email. This is a sort of control.
If you want to register for an event, you have to give your name and your email, it is the same! :-)
There is a possible override together with breezingforms free, which fills you a form with the wished event and then you have to fill this form with your details. What's better?

**Comment by dermaxem** [comment]
for me and the site I build, it should work for any user to register for an event. Events can only be created by a admin. I do not want the user to create a profile. he should click register ( for a event) and fill some fields. new event, he has to fill out again. as on any other Shop-Site u name it. I can order as guest as well, but need to fill some needed Infos, sure. Mit freundlichen Grüßen,Matthias Lach

**Comment by jojo12** [comment]
dann musst du selbst ne Lösung finden!

**Comment by jojo12** [comment]
You're welcome to add this for free!

**Comment by jojo12** [comment]
I looked into the text of the setting: Under Registration, we say "Show attendee names to" "Everybody" or "(only) attending users". We don't speak "event registration to everybody"!

**Comment by Heklaterriol** [comment]
> warum so patzig, es gibt durchaus Komponenten, die das können. Imd wenn ich schon "Everybkdy" wählen kann in den Einstellungen, sollte es auch funktionieren.Mit freundlichen Grüßen,Matthias Lach

Hallo Matthias, wir sind alles Freiwillige, die viele Stunden, Herzblut und auch eigenes Geld investieren, damit alle die wollen diese Extension gratis haben können. Du bist herzlich eingeladen, beizutragen (durch Mitarbeiten, Spenden etc), wenn du JEM um Funktionen erweitern möchtest.

Du hast geschrieben
> es gibt durchaus Komponenten, die das können

Ja das stimmt. JEM ist ein Kalender und eine Event Liste, bisher komplexere Anmeldefunktion. Da die bisherige, einfache Anmeldung in JEM keine Felder für Informationen enthält, ist eine Registrierung der Teilnehmer nötig.
Aber es ist relativ leicht möglich JEM mit BreezingForms oder Chronoforms zu kombinieren und ausgefeilte Anmeldungen zu erstellen, wo die Besucher nicht einmal merken, dass es zwei verschieden Komponenten sind.
