### ISSUE TITLE
CSS Manager: "Option line number" does not work

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#191]
in the CSS Manager
the `Option linenumber` does not work. when clicking on "Click here to enable" or "Click here to disable" it changes status, but it has no effect on the css editor. The line number are alwas there.

In my option we can just leave it way. It is good with line numbers alway on.

**Comment by mckillo** [comment]
I don't see in internal attributes (code) any option to show the number lines. I guess that this option was with old editor in Joomla 1.5.

**Comment by jojo12** [comment]
I think so too!

**Comment by mckillo** [comment]
Proposal .... as Heckla said --- delete this option and line numbers by default.

**Comment by Heklaterriol** [comment]
I removed it

**Comment by Heklaterriol** [comment]
in the CSS manager there is also space for custom css files.

But where should they be to appear here?
I tried all kind of file names and places – no success.
The code is


```
<?php if (!empty($this->files['custom'])) : ?>
  <ul>
    <?php foreach ($this->files['custom'] as $file) : ?>
      <li>
        <?php if ($canDo->get('core.edit')) : ?>
          <a href="<?php echo Route::_('index.php?option=com_jem&task=source.edit&id='.$file->id);?>">
        <?php endif; ?>
        <?php echo Text::sprintf('COM_JEM_CSSMANAGER_EDIT_CSS', $file->name);?>
        <?php if ($canDo->get('core.edit')) : ?>
          </a>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>

```
