### ISSUE TITLE
backend layout settings: color picker does not close properly

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#192]
In the settings the layout color popup panel does not go away until you choose a color or you save the settings.

--> should close when clicking somewhere outside of the panel

**Comment by Heklaterriol** [comment]
Probably time for a newer color picker. 
The embedded one is quite old.

**Comment by jojo12** [comment]
@mckillo nice update

**Comment by mckillo** [comment]
![JEM -Layout -color style](https://user-images.githubusercontent.com/2765316/229730174-dbd7eaef-13c0-4e8b-90c3-c7b0eb3e0f20.jpg)

This is the Joomla Style, do you prefer it? If it's yes, can upload the commit.

**Comment by jojo12** [comment]
where?

**Comment by mckillo** [comment]
In Global Setting - Layout tab - Backgrount color + Border color + Font Color

**Comment by jojo12** [comment]
I meant where can I find the commit? :-)

**Comment by Heklaterriol** [comment]
Yes, it is still the old colorpicker, I just styled the labels and input fields

**Comment by mckillo** [comment]
@jojo12 Here you are. See commit above

**Comment by jojo12** [comment]
the field should be a bit bigger, because now I only see 4 letters (like #ffff instead of #ffffcc)

**Comment by jojo12** [comment]
what about the colorpicker in backend>Category? Could need a refresh too!

**Comment by mckillo** [comment]
Change class="form-control w-25" 
for this one:
class="form-control"
w-25 is 25% and depend of screen resolution, in mobile device is worse.
Now, without w-25, the field is 100% of the container (responsive).

**Comment by mckillo** [comment]
See new commit d5dd714f6bc6056e2b7a9bb3ff465e94020f4e33 that include previous and refresh for colorpicker in backend>Category
