### ISSUE TITLE
countries could be much less!!

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#194]
Only spain instead of kingdom of spain

**Comment by Heklaterriol** [comment]
Yes, we could check how the correct names are today.

But I would not leave any country away - there are people, internet, joomla and events nearly everywhere …

**Comment by jojo12** [comment]
yes, but there are official lists from UN, which are less!

**Comment by jojo12** [comment]
I've just seen now: the choice in the settings are with the short country names. But in events, we have not enough place, but we use extensive country names! We should take the same!

**Comment by mckillo** [comment]
I think that JEM must show all countries. This list is based in norma ISO 3166 (See https://es.wikipedia.org/wiki/ISO_3166)
You can consult the countries list in https://www.iso.org/obp/ui/#search 

![JEM -update countries list with iso 3166](https://user-images.githubusercontent.com/2765316/229762731-8eadd0e9-f847-4022-b754-2d184b3f7407.jpg)


The case of Spain was an example that the names are not right.
We have to update the english name for all countries according to ISO. Do you agree? If it's yes, upload commit.

**Comment by mckillo** [comment]
@jojo12 See commit 07a8b1a09612660f7abfc0a2da8b6dfbf661b872 with names countries updated.
It's valid for new JEM installation.

**Comment by jojo12** [comment]
works fine after new install!
