### ISSUE TITLE
styling forms (cosmetics)

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#198]
I would like to do som cosmetics and style some forms.

But I cannot find where these are generated and how I add some classe to them.

_starttime_, _startminues_, _endtime_, _endminutes_
_venue_ and _contact_, incl labels and buttons

![event-edit-style](https://user-images.githubusercontent.com/28540581/229949561-c558de1f-b23a-46f0-ae90-6394227c41b2.png)

Would you help me out with some hints…?

thx!

**Comment by mckillo** [comment]
![JEM -update event view in backend](https://user-images.githubusercontent.com/2765316/230001616-9787dcb7-d2d7-48ad-b106-bc4303e60c9d.jpg)

A little design, do you like it?

**Comment by mckillo** [comment]
@Heklaterriol See commit above.

**Comment by Heklaterriol** [comment]
Much better. Thank you. I wanted to have it a little more in the bootstrap design. But it is fine like this.

**Comment by mckillo** [comment]
I have upload a aditional committo unify the keys for startdate, enddate, starttime and endtime. Review it.

**Comment by mckillo** [comment]
@Heklaterriol Here you are a new style version 2 using bootstrap .

![JEM -update event view in backend v2](https://user-images.githubusercontent.com/2765316/230061932-cae1d9c7-5680-44a1-8938-99e69eba55ba.jpg)

See commit e50c84c2b9221ff1735453ff268a0d402c74f2ae

**Comment by Heklaterriol** [comment]
very nice, thank you.
