### ISSUE TITLE
No country in backend list of events

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#201]
I just noticed, that the countries are not displayed in the list of event in the backend.

![no-country](https://user-images.githubusercontent.com/28540581/230223399-39d973e8-e20c-4dd4-ba21-e1a7102672aa.png)

**Comment by Heklaterriol** [comment]
I just noted, that in JEM 2.3.5 for J3 there is no country column. So it seems, that we added it – I just don't remember.
I check it out.

**Comment by mckillo** [comment]
Sovled. See commit above.

**Comment by Heklaterriol** [comment]
Thanks, we simultaneously did the same.
