### ISSUE TITLE
2.3.17.3: new deprecated in Backend>events: DateTime

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#202]
deprecated is not error but this comes as new!
I took in Backend a archived event and made a copy with new date and published, then I had 
in creator column  notification, (which went only away after opening and resaving this event).

It linked to a joomla library 

> Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /home/mysite.ch/public_html/libraries/src/Date/Date.php on line 124

(why now?)

This was never before!

**Comment by Heklaterriol** [comment]
Where does it occur?

and `libraries/src/Date/Date.php` is from Joomla not from JEM …

**Comment by Heklaterriol** [comment]
see https://issues.joomla.org/tracker/joomla-cms/36799

**Comment by jojo12** [comment]
Yes, it is from joomla, but I don't understand why to change to a deprecated joomla thing than before?

**Comment by Heklaterriol** [comment]
How can I reproduce it?

By the way: I have many many deprecated messages when I put error reporting to maximum.

**Comment by jojo12** [comment]
I have not so many and I know, that there are deprecated things from joomla.
But here there was no deprecated before and now after the changing it is deprecated. So I would say we changed to something of joomla which is deprecated from something what is not deprecated.
I described how to reproduce!

**Comment by Heklaterriol** [comment]
As fa as I understand:
it is in php 8.1.
JEM hands over to Joomla not correct data (empty field), and the php error reports, that the Joomla functions has a missing parameter …

**Comment by Heklaterriol** [comment]
> I took in Backend a archived event and made a copy with new date and published, then I had
> in creator column notification, (which went only away after opening and resaving this event).

I still cannot reproduce it.

**Comment by mckillo** [comment]
Do you have data to simulate envioroment? (Joomla, php and Jem version).

**Comment by jojo12** [comment]
It was only once, I was not able to reproduce. Can be closed
