### ISSUE TITLE
Clarify and solve the map issues

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#205]
We somehow have to decide what we want to do with the map. And then create a solution.

In the JEM settings we have the following options:
- `No Map Service`
this is clear an no problem
- `Display link to Google Maps`
- `Display Google Map`
- `Display Google map (api-key)`

What is really needed?
What works and what is broken?
And what is the advantage of "Display Google Map" over "Display Google map (api-key)"?

Futher more the _Geodata_ section in _edit venue_ does not work properly.
Not working at the moment:
- checkbox activate/deactivate 
- map display
- button "find by venue data"
- button "Copy data" (address, venue coordinates)

See also:  #109, #81 and #100

**Comment by jojo12** [comment]
testing 
"Display link to google map" shows a icon-button, but clicking on it gives error: "The Google Maps Embed API must be used in an iframe."
"Display google map" AND api-key in api-key field:  shows map in Frontend and map in backend
"Display google map" AND NOT api-key in api-key field:  shows map in Frontend and no map in backend

"Display Google map (api-key)" AND api-key in api-key field: shows no map in Frontend and no map in backend

checkbox activate/deactivate decides if "shows map" or "don't shows map" in frontend  -->works
button "find by venue data" works if api-key is filled in api-key field
with api-key you can move marker and button "only coordinates" works
button "copy data" does not work

I need "moving marker" and save this!
I need "find by venue data"

some of this work only with api-key. But there were always post, which said, there are no more free api-keys from google.

**Comment by Heklaterriol** [comment]
I tried som stuff:
- Google Map link
- Goolge Map iframe witout API key

Works here. Please test.

**Comment by Heklaterriol** [comment]
Note: I correctd it just for the visitors, not in the backend/frontend edit

**Comment by jojo12** [comment]
I tested frontend view.
only google map with api-key setting doesn't work for visitors. 
Google map link is now working!

**Comment by jojo12** [comment]
about geocomplete there are some laters geocomplete from ubilabs

> // # $.geocomplete()
// ## jQuery Geocoding and Places Autocomplete Plugin - V 1.5.0
//
// * https://github.com/ubilabs/geocomplete/

but after this is finished. It's possible to try v.1.7 or looking for an other javascript.

**Comment by jojo12** [comment]
In backend editvenue and frontend edit venue, the map is from geocomplete: normally it shows the map in hybrid modus (satellite with streetnames)
it is possible to move the marker
only the "find with JEM" button and the "only coordinates" works.
the other buttons empty the JEM addresses

**Comment by Heklaterriol** [comment]
an other question:
why should we need the version with the api key?
what is better there compared with the option without api key?

**Comment by jojo12** [comment]
like it is now, the button "show map with api-key" seems to do nothing (I am unsure)
but we need the field to fill in the api-key, because it helps much together with geocomplete to create the map!

**Comment by jojo12** [comment]
I've seen in legacy style that the letters in the input buttons class="geobutton" are half hidden. Should be corrected with height: 40px

**Comment by jojo12** [comment]
I don't understand, why in geocomplete, the fields under the map are not filled I think these fields are used with the buttons, but because they are empty, they empty the JEM fields using the buttons. And the coordinates are only after draging the marker taken back in JEM.

**Comment by jojo12** [comment]
now in 2.3.17.6 it is worse than ever. not usable. That's not to do after 4 release!

**Comment by Heklaterriol** [comment]
What exatcly is worse than before (it should maximally be as bad as before)?
The only things I changed are the **map links**, **iframe link** and **styling of input fields**

**Comment by jojo12** [comment]
map links is ok
iframe link is worse
styling of input fields is ok but more needed is iframe link "Show Google Map"
If interested guest can see only the whole world map, you can forget it.

**Comment by jojo12** [comment]
with this I give green fire for Joomla!4
