### ISSUE TITLE
JEM settings: Meta Options

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#206]
I just discovered the Meta Options in the JEM settings.
What are they good for? 
I'm asking because I cannot see any difference when changing them and in edit events there are specific settings for the events …
![Meta Option](https://user-images.githubusercontent.com/28540581/230654878-1d46072b-a51d-4dba-8860-5c2f82f3d589.png)

**Comment by mckillo** [comment]
![JEM4 meta description of event](https://user-images.githubusercontent.com/2765316/230916555-1953a261-224c-4667-b418-16bae72436ae.jpg)

I tested and it works. The meta description change if I change the date start.

**Comment by Heklaterriol** [comment]
> Other thing, It would be to change the description metadata to event structure with JSON: https://developers.google.com/search/docs/appearance/structured-data/event
> 
> This may be a nice feature for a next version ... for study

Yes definitely. 
I had it once sucessfully implemented on JEM 2.x via override – maybe I find the code again.

I open an new issue.
