### ISSUE TITLE
new bug in event details>Registration> 

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#207]
it's new (perhaps a typo)
clicking on the number of "booked places" I should come to attendee manager, but I get an error:

> syntax error, unexpected token ";", expecting ")"

**Comment by jojo12** [comment]
view/attendees/tmpl/default.php line 193 needs a ) more at the end before ; ?>
`                <?php echo JemOutput::removebutton(JText::_('COM_JEM_ATTENDEES_DELETE'), array('title' => JText::_('COM_JEM_ATTENDEES_DELETE'), 'class' => 'hasTooltip')); ?>
`

**Comment by mckillo** [comment]
@jojo12 Here you are the commit (see above) for your solution.

**Comment by jojo12** [comment]
tested and works fine
