### ISSUE TITLE
Backend, List of events: fresh event without modification date triggers deprecated message (php 8.1)

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#209]
a freshly created event without modification date creates an deprecated message in php 8.1. 

Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /libraries/src/Date/Date.php on line 124

I guess because JEM hands over an empty sting.

**Comment by mckillo** [comment]
With last update admin\views\events\tmpl\default.php, I tested it and works.

![JEM4 - Info autor events view](https://user-images.githubusercontent.com/2765316/231103291-bae74d84-9dca-4c3d-8c33-328d9e0de772.jpg)

2 small things (style issue):
- Change the format DATE_FORMAT_LC4 toDATE_FORMA_LC5, to see the HH:MM data.
-No add \<br\>in the begining, so tou avoid having a larger window (popup).
You can see the comparation of old version, your version (with and witout modified data), and last, myproposal with 2 small changes.

**Comment by mckillo** [comment]
@Heklaterriol It would be necessary to change the admin\views\venues\tmpl\default.php file as well with this change.
