### ISSUE TITLE
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /modules/mod_jem/helper.php on line 134

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#210]
in frontend JEM - Module-Basic

**Comment by Heklaterriol** [comment]
Please check the fix if correct

**Comment by mckillo** [comment]
![JEM4 - Info autor events view](https://user-images.githubusercontent.com/2765316/231095258-259a8d49-8d25-4645-bf7e-7de02604f5e3.jpg)

Tested, it works but 2 things:
- Change the format DATE_FORMAT_LC4 to DATE_FORMAT_LC5, to see the HH:MM data.
- Not add <br> in the begining, so you avoid having a larger window. Small details, it's a style issue, not important.

Yo can see the comparation of old version, your version and new version (my proposal).

**Comment by Heklaterriol** [comment]
Thanks McKillo, I follow you recommondation – you are the coder :-)
