### ISSUE TITLE
"JUri::root" etc. still allowed in Joomla 4?

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#213]
I found several instances and thought it has changed to `Uri::root` (and all other `JUri::` to `Uri::`)

**Comment by mckillo** [comment]
Yes, in the jem\site there is one. I look at it and change it to URI (J4&J5)

**Comment by Heklaterriol** [comment]
I searched over the whole JEM package:
35 instances of "JUri" (and additional 4 in comments)

**Comment by mckillo** [comment]
@Heklaterriol Upload commit with the change to uri of Joomla 4 (see above).

**Comment by Heklaterriol** [comment]
Thanks!

**Comment by Heklaterriol** [comment]
Just noted that there are still many instances of `JUri::root()`, `JUri($link1)`, `JUri::base(true)`, `JUri::getInstance()`, `JUri::isInternal($link)` …

**Comment by mckillo** [comment]
Here you are, no more JUri::
See commit above

**Comment by mckillo** [comment]
A lot of changes. If you see any issue about path, let's me know to debug it.

**Comment by Heklaterriol** [comment]
Thank you.
I just do not know if the `JUri` instances will be a problem soon or if it is ok to leave them.
What do you say?

**Comment by mckillo** [comment]
Uri is new name for JUri (See https://docs.joomla.org/URLs_in_Joomla). 
Now, There isn't any JUri in the JEM code, all reference were changed and I suppose that is better now, because because sooner or later it would have to be changed.

**Comment by jojo12** [comment]
as long as I tested, I didn't encounter such problems.

**Comment by Heklaterriol** [comment]
No errors.
Fine for me like this
