### ISSUE TITLE
new: reset in venueslist doesn't work

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#215]
new: reset in venueslist doesn't work anymore

**Comment by Heklaterriol** [comment]
I don't understand. What exactly are you resetting? and in the backend or frontend?
More details please.

**Comment by jojo12** [comment]
i made a com_jem.zip from the jem_beta_2 and uploaded it over the pkg_jem_v2.3.17.6
That means, I didn't made a whole new package, only the com_jem, because the rest was nothing new.
(I only wanted to say this, because I had this reaction. But after it went away. (I think you can let it, if you don't encounter this.

**Comment by jojo12** [comment]
in legacy it works fine, the problem is only in default style

**Comment by Heklaterriol** [comment]
Please check the fix
