### ISSUE TITLE
1062 Duplicate entry 'defaultCountry' for key 'PRIMARY'

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#216]
I was able to find the call stack: (It was in a test in Joomla!4.3RC3)
 
Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php:442
2 | Joomla\Database\Mysqli\MysqliStatement->execute() | JROOT\libraries\vendor\joomla\database\src\DatabaseDriver.php:675
3 | Joomla\Database\DatabaseDriver->execute() | JROOT\components\com_jem\classes\config.class.php:220
4 | JemConfig->store() | JROOT\administrator\components\com_jem\models\settings.php:101
5 | JemModelSettings->store() | JROOT\administrator\components\com_jem\controllers\settings.php:123
6 | JemControllerSettings->save() | JROOT\libraries\src\MVC\Controller\BaseController.php:678
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_jem\jem.php:56
8 | require_once() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:361
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:143
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:186
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:293
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:61
15 | require_once() | JROOT\administrator\index.php:32

and
Vorheriger Fehler
Duplicate entry 'defaultCountry' for key 'PRIMARY'
                                        

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php:435
2 | mysqli_stmt->execute() | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php:435
3 | Joomla\Database\Mysqli\MysqliStatement->execute() | JROOT\libraries\vendor\joomla\database\src\DatabaseDriver.php:675
4 | Joomla\Database\DatabaseDriver->execute() | JROOT\components\com_jem\classes\config.class.php:220
5 | JemConfig->store() | JROOT\administrator\components\com_jem\models\settings.php:101
6 | JemModelSettings->store() | JROOT\administrator\components\com_jem\controllers\settings.php:123
7 | JemControllerSettings->save() | JROOT\libraries\src\MVC\Controller\BaseController.php:678
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_jem\jem.php:56
9 | require_once() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:361
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:143
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:186
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:293
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:61
16 | require_once() | JROOT\administrator\index.php:32

**Comment by jojo12** [comment]
my question: has this to do with the following changing:
earlier in the default country field there was always "NO VALID COUNTRY", when you had no country
Now there is: "Select Country"  (and it has as an other possibility "NO VALID COUNTRY)

**Comment by jojo12** [comment]
The same is in backend create venue. In the field country there is now "Select Country", when in the settings no country  is selected.
but then I have the error:
Warning: Undefined property: stdClass::$defaultCountry in mysite.ch\administrator\components\com_jem\models\venue.php on line 196

**Comment by Heklaterriol** [comment]
What should we do with this?
I cannot reproduce it.

**Comment by jojo12** [comment]
So we let it!
