### ISSUE TITLE
google maps case 2: not possible anymore to change language ($lg) and top level domain ($tld)

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#218]
at least change language ($lg) should be possible to change. It seems, you set it to $lg=de!
I don't know, what the top level domain changes (when you choose e.g. maps.google.ch instead of maps.google.com, but this had surely a reason why)

**Comment by Heklaterriol** [comment]
Yes, I see: with latitude and longitude the top level domain was fixed. 
The language should be fine.

**Comment by Heklaterriol** [comment]
please test

**Comment by Heklaterriol** [comment]
and the langauge correction, see https://github.com/Heklaterriol/JEM-Project/commit/575787a8c19e5985ac3b63313f6eb17dbcc3e662

**Comment by Heklaterriol** [comment]
please test

**Comment by jojo12** [comment]
its really interesting:
![grafik](https://user-images.githubusercontent.com/2960236/232565762-3f6d4dad-352b-425b-b873-7a06830820fe.png)

the first is the map in venue of event details: this works now with the JEM settings 
the second is the map in venue details. In your fix this uses $tld='com' and $lg='en' (I think the fall back settings)
I made now visible the settings in global parameters/venues and set there $tld='ch' and $lg='de' and now
it is like I set!
when I look into the settings, then the setting in"event page" are fields are named "event_tld" and "event_lg",
meanwhile the fields in  global parameters/venues are named "global_tld" and "global_lg".
So this seems to use different settings!!!

**Comment by jojo12** [comment]
I think, you have to display visible:
line 53 and 54 in default_parameters.php
`<li id="globalmap1" style="display:none"><?php echo $this->form->getLabel('global_tld',$group); ?> <?php echo $this->form->getInput('global_tld',$group); ?></li>
<li id="globalmap2" style="display:none"><?php echo $this->form->getLabel('global_lg',$group); ?> <?php echo $this->form->getInput('global_lg',$group); ?></li>
`
change to:
`<li><?php echo $this->form->getLabel('global_tld',$group); ?> <?php echo $this->form->getInput('global_tld',$group); ?></li>
<li><?php echo $this->form->getLabel('global_lg',$group); ?> <?php echo $this->form->getInput('global_lg',$group); ?></li>
`

**Comment by Heklaterriol** [comment]
there are two different settings for maps:

1.  in > `Settings` > `Edit page` in the section `Venues`
2. in > `Settings` > `Global Parameters` in the section `Venues`

Does this make sense?

**Comment by jojo12** [comment]
I don't know, but it needs more work on this than to hide settings! Adaption of venue detail part to use the same params like event pag

**Comment by Heklaterriol** [comment]
@jojo12 
You wrote:

> I think, you have to display visible: line 53 and 54 in default_parameters.php `
> 
> ```
> form->getLabel('global_tld',$group); ?> form->getInput('global_tld',$group); ?>
> form->getLabel('global_lg',$group); ?> form->getInput('global_lg',$group); ?>
> ```
> change to:
> ```
> form->getLabel('global_tld',$group); ?> form->getInput('global_tld',$group); ?>
> form->getLabel('global_lg',$group); ?> form->getInput('global_lg',$group); ?>
> ```

My question:
As the lines are identical – What is your suggestion?

**Comment by jojo12** [comment]
Sorry, I want to say, you have to make visible this setting. If the <li...> is specified as not visible then noone can choose $tld and $lg for the venue page, so this will always be the default!

**Comment by jojo12** [comment]
I made it please have a look!

**Comment by Heklaterriol** [comment]
OK, I got it.
in JEM 2.3.5 for J3 these fields in the Global Parameters are only displayed when `Display link to Google Maps` or `Display Google Map` is selected, but not with no map or `Display Google map (api-key)`
And this function does not work anymore in JEM4.
I try to fix this.

But I still don't understand, what it is good for to have global settings for maps in the venue display and extra settings for event display …

**Comment by jojo12** [comment]
For me I can agree to use the same, but then we have to change more in venue details! I don't know how much work!

**Comment by Heklaterriol** [comment]
I would remove the parameters in the event settings and keep them in the gobal settings.
Then replace the instances where ther are event parameters with the global parameters.

**Comment by jojo12** [comment]
I hope, you'll succeed!

**Comment by jojo12** [comment]
@Heklaterriol:  why do you use the old files from master?

**Comment by jojo12** [comment]
inside of "remove-event-map-parameter"

**Comment by jojo12** [comment]
now it's welldone! can be closed
