### ISSUE TITLE
Frontend>choose invited user

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#22]
Frontend new event>choose invited :

JHtmlJemhtml not found.

**Comment by jojo12** [comment]
there comes a modal window, you can choose, but the modal persists.

**Comment by Heklaterriol** [comment]
error in
components/com_jem/views/editevent/tmpl/responsive/chooseusers.php:122 

line 122 `<?php echo JHtml::_('jemhtml.toggleAttendanceStatus', 0, $row->status, false); ?>`

**Comment by Heklaterriol** [comment]
see: https://jem4.datenablage.info/submit/editevent.html?layout=chooseusers&tmpl=component&function=jSelectUsers_jform_invited
