### ISSUE TITLE
not like you think it should: archive

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#224]
I have two simplelists (A and B) which use different categories (A with category D, B with category E). When I go with the icon to the archive, I am always in the same simplelist (A with category D).

I think, it should go to the used simplelist (in A to archive A, and in B to archive B).

EDIT:
I tested, the icon button for archive is using wrong simplelist itemIDs! This should be changed, meanwhile I can live knowing this!

**Comment by mckillo** [comment]
Fix with commit 3d6c2e79cbd8d84c1d0e3167a10f779e82446212. Check it.

**Comment by jojo12** [comment]
can be closed as fixed
