### ISSUE TITLE
It is not possible to save the settings after installation

### ISSUE THREAD

**Issue by GiBill** [Heklaterriol/JEM-Project#24]
attempt to assign property css_backend_usecustom on string
after changing some values in the db, it was possible to save new settings

I am testing
notebook with
xampp-windows-x64-8.0.25-0-VS16-installer
Joomla 4.2.6
PHP 8.0.25

**Comment by jojo12** [comment]
refer #17

**Comment by jojo12** [comment]
<html><body>
<blockquote class="blockquote">
                            <span class="badge bg-secondary">0</span>
                            Attempt to assign property "css_backend_usecustom" on string                        </blockquote>
                                                    <div>
                                

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\registry\src\Registry.php:766
2 | Joomla\Registry\Registry->bindData() | JROOT\libraries\vendor\joomla\registry\src\Registry.php:761
3 | Joomla\Registry\Registry->bindData() | JROOT\libraries\vendor\joomla\registry\src\Registry.php:302
4 | Joomla\Registry\Registry->loadObject() | JROOT\components\com_jem\classes\config.class.php:150
5 | JemConfig->bind() | JROOT\administrator\components\com_jem\models\settings.php:95
6 | JemModelSettings->store() | JROOT\administrator\components\com_jem\controllers\settings.php:121
7 | JemControllerSettings->save() | JROOT\libraries\src\MVC\Controller\BaseController.php:672
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_jem\jem.php:51
9 | require_once() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:355
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:143
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:186
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:294
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:61
16 | require_once() | JROOT\administrator\index.php:32

</div>
</body>
</html>
