### ISSUE TITLE
recurrence events

### ISSUE THREAD

**Issue by GiBill** [Heklaterriol/JEM-Project#25]
after selecting weekly, the date (repeat until) is not displayed immediately. It only becomes visible the second time you open it.
But above it says "nothing" instead of "weekly".

the date (Mi, 11. Januar 2023) is fix

**Comment by jojo12** [comment]
(testing this in frontend is not possible)
in backend I can reproduce this issue: 
when I edit an existing event, then it shows only "weekly" and no second line "until".
Then I get the save problem. (#3)
But going back to the event, it is marked as recurrent. But it shows as recurrrent "nothing" and then it shows the second line "until" with the actual date. It is not possible to change this date.
