### ISSUE TITLE
Collection of deprecation notifications

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#27]
with error reports=maximum (deprecated means is working now, but on later phps will not work anymore.)

BACKEND
Function strftime() is deprecated in components/com_jem/classes/output.class.php on line 1223

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in libraries/vendor/joomla/registry/src/Format/Json.php on line 54

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in administrator/components/com_jem/models/event.php on line 126

Deprecated: Function strftime() is deprecated in administrator/components/com_jem/models/fields/calendarjem.php on line 47

Deprecated: Function strftime() is deprecated in components/com_jem/helpers/helper.php on line 696
Deprecated: Function strftime() is deprecated in /libraries/src/HTML/HTMLHelper.php on line 1076
Deprecated: base64_decode(): Passing null to parameter #1 ($string) of type string is deprecated in administrator/components/com_jem/models/source.php on line 40

Notice: file_get_contents(): Read of 8192 bytes failed with errno=21 Is a directory in administrator/components/com_jem/models/source.php on line 126
FRONTEND
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/eventslist/view.html.php on line 173
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in components/com_jem/helpers/helper.php on line 1739

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/event/view.html.php on line 187

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/folktanz/public_html/components/com_jem/views/event/view.html.php on line 334
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/venueslist/view.html.php on line 171
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/venue/view.html.php on line 354
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in libraries/vendor/joomla/registry/src/Format/Json.php on line 54

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/editevent/view.html.php on line 202

Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in components/com_jem/views/editevent/tmpl/responsive/edit.php on line 31
Deprecated: Function strftime() is deprecated in components/com_jem/models/fields/calendarjem.php on line 47
Deprecated: Function strftime() is deprecated in components/com_jem/helpers/helper.php on line 696
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/editvenue/view.html.php on line 180 
Deprecated: Function strftime() is deprecated in components/com_jem/views/calendar/view.html.php on line 84

Deprecated: Function strftime() is deprecated in components/com_jem/views/calendar/view.html.php on line 85

Deprecated: Function strftime() is deprecated in components/com_jem/models/calendar.php on line 58

Deprecated: Function strftime() is deprecated in components/com_jem/models/calendar.php on line 59

Deprecated: Function strftime() is deprecated in components/com_jem/models/calendar.php on line 61

Deprecated: Function strftime() is deprecated in components/com_jem/models/calendar.php on line 62

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/calendar/view.html.php on line 136
Deprecated: Function strftime() is deprecated in components/com_jem/views/calendar/tmpl/responsive/default.php on line 54

Deprecated: Function strftime() is deprecated in components/com_jem/views/calendar/tmpl/responsive/default.php on line 55

Deprecated: Function strftime() is deprecated in components/com_jem/views/calendar/tmpl/responsive/default.php on line 56

Deprecated: Automatic conversion of false to array is deprecated in components/com_jem/classes/calendar.class.php on line 299

Deprecated: Automatic conversion of false to array is deprecated in components/com_jem/classes/calendar.class.php on line 303

Deprecated: Automatic conversion of false to array is deprecated in components/com_jem/classes/calendar.class.php on line 307

Deprecated: Automatic conversion of false to array is deprecated in components/com_jem/classes/calendar.class.php on line 908 

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/weekcal/view.html.php on line 119

Deprecated: Function strftime() is deprecated in components/com_jem/views/weekcal/tmpl/responsive/default.php on line 40

Deprecated: Function strftime() is deprecated in components/com_jem/views/weekcal/tmpl/responsive/default.php on line 49

Deprecated: Function strftime() is deprecated in components/com_jem/views/weekcal/tmpl/responsive/default.php on line 50

Deprecated: Function strftime() is deprecated in components/com_jem/views/weekcal/tmpl/responsive/default.php on line 51

Deprecated: Automatic conversion of false to array is deprecated in components/com_jem/classes/calendar.class.php on line 299

Deprecated: Automatic conversion of false to array is deprecated in components/com_jem/classes/calendar.class.php on line 303

Deprecated: Automatic conversion of false to array is deprecated in components/com_jem/classes/calendar.class.php on line 307

Deprecated: Function strftime() is deprecated in components/com_jem/views/weekcal/tmpl/responsive/default.php on line 49

Deprecated: Function strftime() is deprecated in components/com_jem/views/weekcal/tmpl/responsive/default.php on line 50

Deprecated: Function strftime() is deprecated in components/com_jem/views/weekcal/tmpl/responsive/default.php on line 51

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/myattendances/view.html.php on line 160

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/myevents/view.html.php on line 179
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/myvenues/view.html.php on line 169
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/venue/view.html.php on line 354

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/event/view.html.php on line 187

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in components/com_jem/views/event/view.html.php on line 334

MODULES AND PLUGINS
Deprecated: Function strftime() is deprecated in plugins/content/jemlistevents/jemlistevents.php on line 260

Deprecated: Function strftime() is deprecated in modules/mod_jem_wide/helper.php on line 202

Deprecated: Function strftime() is deprecated in modules/mod_jem_wide/helper.php on line 206

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in components/com_jem/helpers/helper.php on line 1131

Deprecated: Automatic conversion of false to array is deprecated in libraries/src/Document/Document.php on line 600

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in components/com_jem/helpers/helper.php on line 1739

Deprecated: Function strftime() is deprecated in modules/mod_jem_teaser/helper.php on line 293

Deprecated: Function strftime() is deprecated in modules/mod_jem_teaser/helper.php on line 297

Deprecated: Function strftime() is deprecated in modules/mod_jem_teaser/helper.php on line 313

Deprecated: Function strftime() is deprecated in modules/mod_jem_teaser/helper.php on line 379

Deprecated: Function strftime() is deprecated in modules/mod_jem_teaser/helper.php on line 383

Deprecated: Function strftime() is deprecated in modules/mod_jem_banner/helper.php on line 464

Deprecated: Function strftime() is deprecated in modules/mod_jem_banner/helper.php on line 468

Deprecated: Function strftime() is deprecated in modules/mod_jem_cal/helper.php on line 108

Deprecated: Function strftime() is deprecated in modules/mod_jem_cal/helper.php on line 109

Deprecated: Function gmstrftime() is deprecated in modules/mod_jem_cal/tmpl/default.php on line 56

**Comment by Heklaterriol** [comment]
For deprecated messages in modules see also https://jem4.datenablage.info/jem-modules.html

**Comment by Heklaterriol** [comment]
for strftime see https://php.watch/versions/8.1/strftime-gmstrftime-deprecated
