### ISSUE TITLE
legacy frontend>editevent>save

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#29]
Main problem:
legacy frontend>menue eventsubmission:
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>simplelist: clicking on "submit new event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>calendar: clicking on "submit new event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>category: clicking on "submit new event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>categories: clicking on "submit new event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>day: clicking on "submit new event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>venues: clicking on "submit new event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>weekcalendar: clicking on "submit new event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend>menue eventsubmission:
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by Heklaterriol** [comment]
always error in components/com_jem/views/editevent/tmpl/edit.php:65 
line 65 `<?php echo $this->form->getField('articletext')->save(); ?>`

**Comment by jojo12** [comment]
2.3.8 Problem persists: now I get:
0 Call to undefined method Joomla\Component\Finder\Administrator\Indexer\Helper::getContentPath()
