### ISSUE TITLE
Backend>new/edit event problem with JEM smart search plugin!

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#3]
#1295
Backend:
New/edit event>Save -->does save, but not “category” -->there is nothing saved in cat_events!
Error: Call to undefined method Joomla\Component\Finder\Administrator\Indexer\Helper::getContentPath()

**Comment by Heklaterriol** [comment]
cannot reproduce it: can you provide more details

**Comment by jojo12** [comment]
I open in backend events>new event. I choose a title, a date and a category e.g. testcategory (I created before).
Then I save. There comes the error above.
When I go back into backend>events, I see the new event, but with no category. When I look into db, there is nothing new in cat_event!

**Comment by Heklaterriol** [comment]
I treid everything to reproduce it, but I do not get this error – works find here …

**Comment by jojo12** [comment]
did you look in the db?

**Comment by Heklaterriol** [comment]
Yes, everything looks fine …
Please have look at the PM in the JEM board

**Comment by jojo12** [comment]
this problems continues!

**Comment by Heklaterriol** [comment]
could you provide the call stack (when error reporting on maximum)

**Comment by jojo12** [comment]
<html><body>


# | Function | Location
-- | -- | --
1 | () | JROOT\plugins\finder\jem\jem.php:291
2 | plgFinderJEM->index() | JROOT\administrator\components\com_finder\src\Indexer\Adapter.php:360
3 | Joomla\Component\Finder\Administrator\Indexer\Adapter->reindex() | JROOT\plugins\finder\jem\jem.php:172
4 | plgFinderJEM->onFinderAfterSave() | JROOT\libraries\src\Plugin\CMSPlugin.php:279
5 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:486
6 | Joomla\Event\Dispatcher->dispatch() | JROOT\libraries\src\Application\EventAware.php:107
7 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT\plugins\content\finder\finder.php:46
8 | PlgContentFinder->onContentAfterSave() | JROOT\libraries\src\Plugin\CMSPlugin.php:279
9 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:486
10 | Joomla\Event\Dispatcher->dispatch() | JROOT\libraries\src\Application\EventAware.php:107
11 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT\libraries\src\MVC\Model\AdminModel.php:1277
12 | Joomla\CMS\MVC\Model\AdminModel->save() | JROOT\administrator\components\com_jem\models\event.php:328
13 | JemModelEvent->save() | JROOT\libraries\src\MVC\Controller\FormController.php:676
14 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT\libraries\src\MVC\Controller\BaseController.php:672
15 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_jem\jem.php:51
16 | require_once() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71
17 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73
18 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:355
19 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:143
20 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:186
21 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:294
22 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:61
23 | require_once() | JROOT\administrator\index.php:32


</body>
</html>

**Comment by jojo12** [comment]
the same time as deprecatede:

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in C:\xampp\htdocs\joomla_42\libraries\vendor\joomla\registry\src\Format\Json.php on line 54

**Comment by jojo12** [comment]
testing on xampp localhost

**Comment by jojo12** [comment]
result
![newevent](https://user-images.githubusercontent.com/2960236/218301668-5f337a46-8f84-476b-9e30-cab80e44b4d2.png)
