### ISSUE TITLE
legacy frontend event>edit event

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#30]
legacy frontend event>clicking on "edit event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by jojo12** [comment]
the same:
legacy frontend event>clicking on "copy event"
gives error:
0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()

**Comment by Heklaterriol** [comment]
what does "legacy frontend event" mean? Where can I reproduce the error?

**Comment by jojo12** [comment]
In the settings: choose legacy template!
(Sorry your git mails were in my SPAM🤔

**Comment by Heklaterriol** [comment]
I see the edit button only when fontawesome 4 is replaced with fontawesome 5 
or  class `fa-pencile-square-o` is replaced with `fa-pen-square`

**Comment by Heklaterriol** [comment]
Error in components/com_jem/views/editevent/tmpl/edit.php:65 

line 65 `<?php echo $this->form->getField('articletext')->save(); ?>`

**Comment by Heklaterriol** [comment]
the same happens in  the legacy frontend on the submit even page
