### ISSUE TITLE
mod_jem_wide produces error 

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#33]
when trying to display in frontend, mod_jem_wide produces an error 
Class "Text" not found
JROOT/modules/mod_jem_wide/tmpl/responsive/default.php:32

**Comment by Heklaterriol** [comment]
`use Joomla\CMS\Language\Text;` is missing

**Comment by jojo12** [comment]
I had this only once, when there were no active events to show (e.g. all events were archived, this happened, when the example event are outdated)

**Comment by Heklaterriol** [comment]
Yes it is the language string "echo Text::_('MOD_JEM_WIDE_NO_EVENTS');"
