### ISSUE TITLE
Zebra_image could be updated to 2.8.1

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#36]
Zebra_image has updates

**Comment by Heklaterriol** [comment]
is it as simple as it looks like? just replacing the old version (2.6.0) with the new one (2.8.0) in components/com_jem/classes/Zebra_Image.php ?

**Comment by Heklaterriol** [comment]
Zebra_image 2.8.2 is included in the PR branch "small-fixes-before-JEM4"
