### ISSUE TITLE
Backend>Add attendee

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#4]
#1296
Backend:
Events>Reg.Users>New>Add Attendee>Select user> there's no "Save" button!
if there are attendees via Frontend
Events>Reg.Users >Error: JHtmlJemhtml not found.

**Comment by Heklaterriol** [comment]
Events > in the list of events in the column "Reg. Users" click on the number of registered users 
If the number is > 0 there is an error
```
Error: JHtmlJemhtml not found.
in administrator/components/com_jem/views/attendees/tmpl/default.php:117
```
If the number is = 0 there no error
but when you click on New > Add Attendee > Select user:
a modal window should pop up, wher eyou can selsct a name and the modal is then closed again, but instead a new window opens.
Compare defective [jem4](https://jem4.datenablage.info) with working [jem3](https://jem3.datenablage.info)
