### ISSUE TITLE
"my event" page – "submit event" button missing

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#41]
on the "my event" page there is the "submit event" icon missing at the top in the first position in the line of the icons
**Needs frontend login to see**

see:
https://jem3.datenablage.info/my-events.html

missing button:
https://jem4.datenablage.info/my/my-events.html

**Comment by jojo12** [comment]
submit new event is there (see the mouse icon as hand), but the icon is not anymore supported (not fontawesome 5 free)
