### ISSUE TITLE
remove Layout Style "Alternative (Responsive Style)"

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#44]
remove the already disabled layout style "Alternative (Responsive Style)" in com_jem/admin/models/forms/settings.xml on

Line 205: `<option value="2" disabled="disabled">COM_JEM_SHOW_LAYOUT_STYLE_ALTERNATIVE</option>`
`

**Comment by Heklaterriol** [comment]
@jojo12 Waht is the idea of reopening this issue?
Just to have a third possible layout style?

**Comment by jojo12** [comment]
It was in the collection for later! 
It is just away?
