### ISSUE TITLE
Error in frontend when Edit event > save

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#49]
Save failed with the following error:
Incorrect integer value: '' for column `d13b275f`.`jem4_jem_events`.`contactid` at row 1

d13b275f = DB name

error in /components/com_jem/views/editevent/tmpl/edit.php:65

**Comment by Heklaterriol** [comment]
Fontend in Default (Responsive Style) when "Edit event" > save

`Save failed with the following error: Incorrect integer value: '' for column 'd03b475f'.'jem4_jem_events'.'contactid' at row 1`

**Comment by jojo12** [comment]
2.3.7: Trying to Save : 0 Call to a member function format() on bool
