### ISSUE TITLE
No icons with cassiopeia

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#5]
refer #1297 in jemproject
only with cassiopeia
testing on livesite with t4_template they are visible!
Frontend:
In “simplelist” top right icon “submit new event” is invisible
In “day” top right icon “submit new event” is invisible
In “venues” top right icon “submit new event” is invisible
In “event” top right icon“submit new event” and icon “e-mail” are invisible
In “categories” top right icon“submit new event” and icon “e-mail” are invisible
in “venueslist” top right icon “e-mail” is invisible
icon "edit" and "copy" are invisible

EDIT: to change in output.class.php

**Comment by Heklaterriol** [comment]
Do you have some more information, any idea why the icons are not dispalyed?

**Comment by jojo12** [comment]
Bootstrap 5 # has changes vs Bootstrap 4!
