### ISSUE TITLE
time not displayed correctly  

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#52]
e.g.  %12:%Feb h

Wrong time settings, easy to change manually, **but** 
in the sample events SQL import file "install.mysql.utf8.sql" the time format settings are not correct.

is
```
('formattime', '%H:%M'),
('formathour', '%H'),
```

should be
```
('formattime', 'H:i'),
('formathour', 'H'), 
```

**Comment by jojo12** [comment]
I was able to reproduce this issue!

**Comment by Heklaterriol** [comment]
Wrong time settings, easy to change manually, **but** 
in the sample events SQL import file "install.mysql.utf8.sql" the time format settings are not correct

is
```
('formattime', '%H:%M'),
('formathour', '%H'),
```

should be
```
('formattime', 'H:i'),
('formathour', 'H'), 
```

**Comment by jojo12** [comment]
My question is: can the time format be implemented just with the installation for the modules too?
