### ISSUE TITLE
2.3.11: JEM finder plugin persists making problems  (see #134)

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#54]
2.3.7: when trying to save:
0 Call to undefined  method Joomla\Component\Finder\Administrator\Indexer\Helper::getContentPath() 

**EDIT: when I disable JEM smart search this problem disappears**

**Comment by Heklaterriol** [comment]
Cannot reproduce it. Please provide more details.

**Comment by jojo12** [comment]
<html><body>


# | Function | Location
-- | -- | --
1 | () | JROOT/plugins/finder/jem/jem.php:291
2 | plgFinderJEM->index() | JROOT/administrator/components/com_finder/src/Indexer/Adapter.php:360
3 | Joomla\Component\Finder\Administrator\Indexer\Adapter->reindex() | JROOT/plugins/finder/jem/jem.php:172
4 | plgFinderJEM->onFinderAfterSave() | JROOT/libraries/src/Plugin/CMSPlugin.php:279
5 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
6 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:107
7 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/plugins/content/finder/finder.php:46
8 | PlgContentFinder->onContentAfterSave() | JROOT/libraries/src/Plugin/CMSPlugin.php:279
9 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
10 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:107
11 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/libraries/src/MVC/Model/AdminModel.php:1277
12 | Joomla\CMS\MVC\Model\AdminModel->save() | JROOT/administrator/components/com_jem/models/event.php:328
13 | JemModelEvent->save() | JROOT/libraries/src/MVC/Controller/FormController.php:676
14 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
15 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_jem/jem.php:51
16 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
17 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
18 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
19 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
20 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
21 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
22 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
23 | require_once() | JROOT/administrator/index.php:32


</body>
</html>

**Comment by jojo12** [comment]
2.3.8 Problem persists!

**Comment by Heklaterriol** [comment]
I still cannot reporduce it, I tried many different settings.
Is there a accessible installation, where I could reproduce it and also for the coder to check.

**Comment by jojo12** [comment]
Quick solution: disable JEM smart search

**Comment by mckillo** [comment]
JEM Finger plugin is used then Smart Search JEM is active. This error is generated in plugins\finder\jem\jem.php line 291:
`$item->path = FinderIndexerHelper::getContentPath($item->route);`

getContentPath doesn't exist en J4. If this line is commenting, then there is a new error:
Save failed with the following error: Category must have a title.

Into JEM v.2.3.9 for J4, IJEM Finder plugin is the same for J3 and it haven't been migrated to J4. 
Review code, I think, first there is migrate de code for this plugin to "support J4".

**Comment by jojo12** [comment]
@hekla: so the JEM finder plugin must be migrated to Joomla!4

**Comment by jojo12** [comment]
As urgent solution: does it need the Jem smart finder?

**Comment by jojo12** [comment]
what about this last blocker?
