### ISSUE TITLE
Backend>Events List wide

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#55]
2.3.7: I can't reach the end on the right side with my surface! So I can't reach the attendees column (landscape). Never had that.
with portrait it works.

**Comment by Heklaterriol** [comment]
This is a problem, which **we** have to decide/solve not the coder. There are too many columns in the list …
We could use a shorter date formating instead of "Sat, 11. February 2023 - Wed, 15. February 2023" e.g. 11. Feb 23 - 15. Feb 23", hide the "state" column etc
