### ISSUE TITLE
Backend>New attendee

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#56]
Backend>Event>Attendees>new attendee/invite doesn't add chosen person!

**Comment by Heklaterriol** [comment]
Where exactly is Backend>Event>Attendees?

**Comment by jojo12** [comment]
Ø  Is my sign to “choose”

Go to Backend

Go to Events

Choose Attendees

 

Jojo

 

Von: Hekla Terriol ***@***.*** 
Gesendet: Samstag, 4. Februar 2023 23:04
An: Heklaterriol/JEM-Project
Cc: jojo12; Author
Betreff: Re: [Heklaterriol/JEM-Project] Backend>New attendee (Issue #56)

 

Where exactly is Backend>Event>Attendees?

**Comment by jojo12** [comment]
Strange, I don't understand, why this works in your jem4!
