### ISSUE TITLE
backend: the reset-button doesn't reset the date-filter-fields

### ISSUE THREAD

**Issue by GiBill** [Heklaterriol/JEM-Project#62]

**Comment by Heklaterriol** [comment]
which reset button exactly?

**Comment by GiBill** [comment]
backend: events 
views/events/tmpl/default
line 135
JSEARCH_FILTER_CLEAR          = Zurücksetzen

**Comment by jojo12** [comment]
is there a date reset button?

**Comment by jojo12** [comment]
I tested in my JEM 2.3.5 on Joomla3! this didn't work. So it seems this is an enhancement!

**Comment by mckillo** [comment]
I have tested 'clear button' in events view of backend, and it works. 

![JEM for JL4 - events backend - clear button works](https://user-images.githubusercontent.com/2765316/223330196-0295f800-cc80-47a2-b605-351655a31867.jpg)

Any details to simulate the issue?

**Comment by jojo12** [comment]
I don't know this
