### ISSUE TITLE
backend: Start-Date

### ISSUE THREAD

**Issue by GiBill** [Heklaterriol/JEM-Project#63]
admin views/events/tmpl/default
line 285

my suggestion:
$displaytime = substr($row->times,0,5);

**Comment by Heklaterriol** [comment]
What would be the effect of your suggestion?

**Comment by GiBill** [comment]
PHP 8.0.25
settings: strftime    H:M

with this code:   start-time => 19:30       = i.O.

without this code: start-time => 19:Feb

settings: strftime    %H:%M          initial-value after installation
start-time => %19:%Feb

what are the best settings for strftime ?

**Comment by jojo12** [comment]
i think, we can close this issue
