### ISSUE TITLE
Frontend > editevent > Registration >Invited users > select

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#65]
it shows you possible users, you can choose, they are counted, but when you try to save, it shows error
0 Call to a member function format() on bool

**Comment by Heklaterriol** [comment]
Can you set error reporting to maximum and then provide the output of the stack call.

**Comment by jojo12** [comment]
<html><body>


Call stack
--
# | Function | Location
1 | () | JROOT/plugins/finder/jem/jem.php:291
2 | plgFinderJEM->index() | JROOT/administrator/components/com_finder/src/Indexer/Adapter.php:360
3 | Joomla\Component\Finder\Administrator\Indexer\Adapter->reindex() | JROOT/plugins/finder/jem/jem.php:172
4 | plgFinderJEM->onFinderAfterSave() | JROOT/libraries/src/Plugin/CMSPlugin.php:279
5 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
6 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:107
7 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/plugins/content/finder/finder.php:46
8 | PlgContentFinder->onContentAfterSave() | JROOT/libraries/src/Plugin/CMSPlugin.php:279
9 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
10 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:107
11 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/libraries/src/MVC/Model/AdminModel.php:1277
12 | Joomla\CMS\MVC\Model\AdminModel->save() | JROOT/administrator/components/com_jem/models/event.php:328
13 | JemModelEvent->save() | JROOT/libraries/src/MVC/Controller/FormController.php:676
14 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/components/com_jem/controllers/event.php:283
15 | JemControllerEvent->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
16 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_jem/jem.php:48
17 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
18 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
19 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
20 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:200
21 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:241
22 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
23 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
24 | require_once() | JROOT/index.php:32


</body>
</html>

**Comment by jojo12** [comment]
button works, but problem of editevent>save persists!
