### ISSUE TITLE
Frontend > edit event > Attachments 

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#66]
I tried to attach a file, but when trying to save, gives error
0 Call to a member function format() on bool 
(is it possible, that after a first save on editevent, all other changes with saves lead to the same error?)

**Comment by Heklaterriol** [comment]
Where can you attach files in the frontend. I can only see the attachment tab in the FE it there already is an attached file.

**Comment by jojo12** [comment]
You need to choose this possibility in settings! Then you are able.

**Comment by Heklaterriol** [comment]
Cannot reproduce it. tried all kind of ways - no errors. 
Can you set error reporting to maximum and then provide the output of the stack call.

**Comment by jojo12** [comment]
I will be back tomorrow!

**Comment by jojo12** [comment]
(I am back!)
2.3.7.a I was able to add an attachment! (but not to remove)
