### ISSUE TITLE
2.3.9: Frontend : Saving edited event not possible when not in english --> Date problem

### ISSUE THREAD

**Issue by jobrusche** [Heklaterriol/JEM-Project#69]
Frontend>Edit event changing anything  (e.g. "Allow annulation" from no to yes)
Save event ->
![Save-modified-event](https://user-images.githubusercontent.com/117929258/217371003-27f8cd66-89cc-43dc-b201-5ecdab72d846.png)

Environment:
Wampserver 3.3.0 64b - Joomla 4.2.7 - PHP 8.0.13

**Comment by Heklaterriol** [comment]
cannot reproduce.
According to the call stack, it looks as if it isn't a joomla error, right?

**Comment by jobrusche** [comment]
I'm running JEM4-beta1, did I report against de wrong  code pool ?

**Comment by Heklaterriol** [comment]
The versioning it not set up 100% clearly – sorry for that.
We already have had 3 versions of "JEM4-beta1" 
- 1. round: 2.3.6
- 2. round: 2.3.7
- minor correction to 2. round: 2.3.7a

**Comment by jojo12** [comment]
<html><body>


Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Form/Field/CalendarField.php:401
2 | Joomla\CMS\Form\Field\CalendarField->filter() | JROOT/libraries/src/Form/Form.php:1047
3 | Joomla\CMS\Form\Form->filter() | JROOT/libraries/src/Form/Form.php:991
4 | Joomla\CMS\Form\Form->process() | JROOT/libraries/src/MVC/Model/FormModel.php:213
5 | Joomla\CMS\MVC\Model\FormModel->validate() | JROOT/libraries/src/MVC/Controller/FormController.php:623
6 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/components/com_jem/controllers/event.php:283
7 | JemControllerEvent->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_jem/jem.php:48
9 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:200
13 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:241
14 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
16 | require_once() | JROOT/index.php:32


</body>
</html>

**Comment by jojo12** [comment]
2.3.8 Problem persists!

**Comment by jobrusche** [comment]
Confirming: with 2.3.8 still dumping stack

**Comment by jojo12** [comment]
I edited an event on your JEM4, I changed featured from yes to no, then save:
I got:
danger
Save failed with the following error: Incorrect integer value: '' for column `d03b475f`.`jem4_jem_events`.`locid` at row 1

**Comment by jojo12** [comment]
I try the same "edit an existing event in frontend" in my installation:
when JEM smart search is activated, then I get: 

> 0 Call to a member function format() on bool

when JEM smart search ist deactivated, then I get:

> Save failed with the following error: Incorrect integer value: '' for column d03b475f.jem4_jem_events.locid at row 1

**Comment by jojo12** [comment]
Logs:
2023-02-22T12:42:12+00:00	INFO 127.0.0.1	controller	Releasing edit ID com_jem.edit.event.24 Array ( ) 
2023-02-22T12:43:56+00:00	INFO 127.0.0.1	controller	Holding edit ID com_jem.edit.event.24 Array (     [0] => 24 ) 
2023-02-22T12:43:57+00:00	INFO 127.0.0.1	controller	Checking edit ID com_jem.edit.event.24: 1 Array (     [0] => 24 )

**Comment by jojo12** [comment]
![error](https://user-images.githubusercontent.com/2960236/220627086-3f8d46ab-e10f-48a6-aa46-b7a3265b06d2.png)

**Comment by jojo12** [comment]
I think, in JEM4 you are on the right way: the input date must be yyyy--mm-dd. This is a common joomla problem!

**Comment by jobrusche** [comment]
Frontend : create new event -> save ->OK
Edit same event (changed start + end time) -> save -> 0 - Call to a member function format() on bool
Log:
#<?php die('Forbidden.'); ?>
#Date: 2023-02-22 16:08:20 UTC
#Software: Joomla! 4.2.8 Stable [ Uaminifu ] 16-February-2023 15:00 GMT

#Fields: datetime	priority clientip	category	message
2023-02-22T16:08:20+00:00	CRITICAL 2a02:a03f:8b9f:f900:ccb3:1a37:941b:fdb9	error	Uncaught Throwable of type Error thrown with message "Call to a member function format() on bool". Stack trace: #0 [ROOT]/libraries/src/Form/Form.php(1047): Joomla\CMS\Form\Field\CalendarField->filter('30-11--0001', NULL, Object(Joomla\Registry\Registry))
#1 [ROOT]/libraries/src/Form/Form.php(991): Joomla\CMS\Form\Form->filter(Array, NULL)
#2 [ROOT]/libraries/src/MVC/Model/FormModel.php(213): Joomla\CMS\Form\Form->process(Array, NULL)
#3 [ROOT]/libraries/src/MVC/Controller/FormController.php(623): Joomla\CMS\MVC\Model\FormModel->validate(Object(Joomla\CMS\Form\Form), Array)
#4 [ROOT]/components/com_jem/controllers/event.php(283): Joomla\CMS\MVC\Controller\FormController->save('id', 'a_id')
#5 [ROOT]/libraries/src/MVC/Controller/BaseController.php(672): JemControllerEvent->save()
#6 [ROOT]/components/com_jem/jem.php(48): Joomla\CMS\MVC\Controller\BaseController->execute('save')
#7 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(71): require_once('/var/www/client...')
#8 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(73): Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}('/var/www/client...')
#9 [ROOT]/libraries/src/Component/ComponentHelper.php(355): Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()
#10 [ROOT]/libraries/src/Application/SiteApplication.php(200): Joomla\CMS\Component\ComponentHelper::renderComponent('com_jem')
#11 [ROOT]/libraries/src/Application/SiteApplication.php(241): Joomla\CMS\Application\SiteApplication->dispatch()
#12 [ROOT]/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\SiteApplication->doExecute()
#13 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#14 [ROOT]/index.php(32): require_once('/var/www/client...')
#15 {main}
2023-02-22T16:13:21+00:00	CRITICAL 2a02:1210:3aef:100:4048:d393:ec86:b27e	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Pagina niet gevonden". Stack trace: #0 [ROOT]/libraries/src/Application/SiteApplication.php(736): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]/libraries/src/Application/SiteApplication.php(224): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('/var/www/client...')
#5 {main}
2023-02-22T16:13:44+00:00	CRITICAL 2a02:1210:3aef:100:4048:d393:ec86:b27e	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Pagina niet gevonden". Stack trace: #0 [ROOT]/libraries/src/Application/SiteApplication.php(736): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]/libraries/src/Application/SiteApplication.php(224): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('/var/www/client...')
#5 {main}
2023-02-22T16:14:44+00:00	CRITICAL 2a02:a03f:8b9f:f900:ccb3:1a37:941b:fdb9	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Pagina niet gevonden". Stack trace: #0 [ROOT]/libraries/src/Application/SiteApplication.php(736): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]/libraries/src/Application/SiteApplication.php(224): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('/var/www/client...')
#5 {main}
2023-02-22T16:17:16+00:00	CRITICAL 2a02:a03f:8b9f:f900:ccb3:1a37:941b:fdb9	error	Uncaught Throwable of type Error thrown with message "Call to a member function format() on bool". Stack trace: #0 [ROOT]/libraries/src/Form/Form.php(1047): Joomla\CMS\Form\Field\CalendarField->filter('30-11--0001', NULL, Object(Joomla\Registry\Registry))
#1 [ROOT]/libraries/src/Form/Form.php(991): Joomla\CMS\Form\Form->filter(Array, NULL)
#2 [ROOT]/libraries/src/MVC/Model/FormModel.php(213): Joomla\CMS\Form\Form->process(Array, NULL)
#3 [ROOT]/libraries/src/MVC/Controller/FormController.php(623): Joomla\CMS\MVC\Model\FormModel->validate(Object(Joomla\CMS\Form\Form), Array)
#4 [ROOT]/components/com_jem/controllers/event.php(283): Joomla\CMS\MVC\Controller\FormController->save('id', 'a_id')
#5 [ROOT]/libraries/src/MVC/Controller/BaseController.php(672): JemControllerEvent->save()
#6 [ROOT]/components/com_jem/jem.php(48): Joomla\CMS\MVC\Controller\BaseController->execute('save')
#7 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(71): require_once('/var/www/client...')
#8 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(73): Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}('/var/www/client...')
#9 [ROOT]/libraries/src/Component/ComponentHelper.php(355): Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()
#10 [ROOT]/libraries/src/Application/SiteApplication.php(200): Joomla\CMS\Component\ComponentHelper::renderComponent('com_jem')
#11 [ROOT]/libraries/src/Application/SiteApplication.php(241): Joomla\CMS\Application\SiteApplication->dispatch()
#12 [ROOT]/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\SiteApplication->doExecute()
#13 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#14 [ROOT]/index.php(32): require_once('/var/www/client...')
#15 {main}

Joomla 4.2.8 / PHP 8.0.32 / JEM beta4 2.3.8   https://wega.brusche.be

**Comment by jojo12** [comment]
for me this is the releaseblocker! (is it in models/fields/calendarjem.php?)

**Comment by jojo12** [comment]
In a clean Joomla! I don't have this problem! So it seems fixed, but because it's important, we should know what it is!!!
I think it's the Calendar field problem! But how!

**Comment by jobrusche** [comment]
Still a problem with beta4-2.39 on wega.brusche.be

**Comment by jojo12** [comment]
@jobrusche: Do you test on a clean Joomla!4.2.8 with no other extension, temlate, plugin?
I tested on my active site, and I have the same problem. Then I tested on a clean site, and it works. So my conclusion is an interference with other extensions!

**Comment by jobrusche** [comment]
Besides JEM this site has: Joomal 4.2.8 / Akeeba backup / JCE /  Phoca download / Allrounder template(from bakual.net)

**Comment by jojo12** [comment]
quick solution, when nothing changed: change frontend language to english!

**Comment by jobrusche** [comment]
Checked this on fresh installed Joomla 4.2.8 not other components than JEM beta4 2.39
Changed  language from Dutch to English ->> success 
Also on wega.brusche.be, changed frontend language from Dutch to English ->> success

**Comment by jojo12** [comment]
@mckillo: Hi, I wrote it here earlier one possibility of notification is:
I got this with: legacy stile: frontend>editevent (existing event)>save
Save failed with the following error: Incorrect integer value: '' for column d03b475f.jem4_jem_events.locid at row 1

**Comment by jojo12** [comment]
When languages set in english, then frontend>editevent has dateformat 2023-03-02 and saving is ok!
when langueages set in german, then frontend>editevent has dateformat 02.03.2023 and saving gets error!

**Comment by jojo12** [comment]
When I remember right, this was a big problem too in times of new Joomla! 3.6. And I think perhaps because of this there is calendarjem.php.

**Comment by mckillo** [comment]
I have debugged the cause. 

![JEM for JL4 - recurrence_limit_date generate errorin other languages when this filed value in db is 0000-00-00 ](https://user-images.githubusercontent.com/2765316/222923152-38107d71-18a9-4121-99ad-1f96d19e7808.jpg)

When you create the first event (title, date and category), save, don't have any error. 
This event was save with _jem_events.recurrence_limit_date to '0000-00-00', and it should be 'null', because this field wasn't define in the event edit page (Extended tab).
If edit this event and save, you have the error. If you change en DB _jem_events.recurrence_limit_date= null for this event (this field can be null, see structure table). It works. 
If  JEM validate date and format, the validate process is made by Joomla 4 and the date format = '0000-00-00' isn't valid, because its value="30-11--0001". This is the value of this field when the event edit and when save the event has the error.

If you create a new event with recurrence, don't have any error. In this case recurrence_limit_date has a valid value, it isn't 0000-00-00.

One commit of import process, it's migrate this data from JEM2.3.5 '0000-00-00' to null (see 70faf5c4c255e232bbdc27b71e9f991acf9e0b04) So, when the admin edits old event, don't have any error when save.

Today, I don't have time more. The solution is easy, when this field "Recurrence counter" isn't defined (not used), it muest save its value as null in the DB. I suppose with this hint, hekla can easily fix it :-)

**Comment by jojo12** [comment]
For the first view: Gracias!

**Comment by mckillo** [comment]
@jojo12: Here you are the fix
When a new event is saved and recurrence isn't used (defined), the  recurrence_limit_date field of event must be null.
recurrence_limit_date field is defined into event table structure as null instead of 0000-00-00

In the administrator\components\com_jem\models\event.php line290, change this line:
`$data['recurrence_limit_date'] = '0000-00-00';`
for this one:
`$data['recurrence_limit_date'] = null;`

Review and testing. See commit abcb4f4105cdf6915c119d79f2a411898e24d041)

**Comment by jojo12** [comment]
I tested with mckillos commit, works best! Thanks

**Comment by jojo12** [comment]
see mckillos commit

**Comment by Heklaterriol** [comment]
I appled the changes: 

_In the administrator\components\com_jem\models\event.php line290, change this line:
`$data['recurrence_limit_date'] = '0000-00-00';`
for this one:
`$data['recurrence_limit_date'] = null;`_

The error still exits at my site …

**Comment by Heklaterriol** [comment]
In `/com_jem/media/js/unlimited.js` line 18-24 I found:

```
function submit_unlimited() {
	var $value = document.getElementById("recurrence_limit_date").value;
	var $date_array = $value.split("-");
	if ($date_array.length < 3) {
		document.getElementById("recurrence_limit_date").value = "0000-00-00";
	}
}

```

This should be changed too I guess.

to `document.getElementById("recurrence_limit_date").value = "";` or what is best?

**Comment by mckillo** [comment]
@Heklaterriol The error exits in the event created, in the new event doesn't exist. 
In the eventcreated, you must change this field into database (_jem_events.recurrence_limit_date to '0000-00-00', and it should be 'null').
It's important too, to change this data into import process (see https://github.com/Heklaterriol/JEM-Project/commit/70faf5c4c255e232bbdc27b71e9f991acf9e0b04), because in JEM 2.3.5, _jem_events.recurrence_limit_date to '0000-00-00' (by default), in all event don't use recurrence.

**Comment by mckillo** [comment]
Respect /com_jem/media/js/unlimited.js, 
If recurrence_limit_date value is null, don't have to do any split. 
And you are right, if <3 value must be "".
Onen details: I don't found in code the call to `function submit_unlimited`. I think, that it doesn't used. Check it.
