### ISSUE TITLE
Email to a friend 

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#7]
#1300
Frontend
Event>Top right E-Mail --> doesn’t work: PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE
Venue> Top right E-Mail -->doesn’t work: PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE

**Comment by Heklaterriol** [comment]
PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE in english "An error occurred while updating the database"

**Comment by jojo12** [comment]
I know, strange is, that the error comes as key!

**Comment by Heklaterriol** [comment]
I get "404 Component not found" under the link https://jem4.datenablage.info/component/mailto/?tmpl=component&template=cassiopeia …

**Comment by Heklaterriol** [comment]
@jojo12: I cannot reproduce your error, I just get page with a "404 Component not found" message …
