### ISSUE TITLE
2.3.9: blindtext date/enddate is wrong

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#72]
2.3.7.a: blindtext date/enddate is wrong  (frontend eventedit/eventsubmission)
![blindtext_date](https://user-images.githubusercontent.com/2960236/218044779-22301523-5eff-4790-b3d8-4ddcbc7c0628.png)

**Comment by jojo12** [comment]
problem persists in 2.3.8!

**Comment by mckillo** [comment]
I think that Heklarriol fix to site view (it's right for the issue),and jojo12 reopen for the admin viwe.
Now, it's fix in the admin view with this commit 6717e040d6538e8df16412a8316b57f3dddef0dd
@jojo12: if it's right, add next version and close issue.
