### ISSUE TITLE
Add attending user in backend works only when debug is enabled :-(

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#74]
2.3.7.a events>click on attending number>add attendee>choose a user, try to save. Nothing happens!

**Comment by Heklaterriol** [comment]
cannot reproduce, see:
https://user-images.githubusercontent.com/28540581/218122663-920be6de-9708-4031-8fc8-9e2568aae636.mov

Is this what you meant?

**Comment by jojo12** [comment]
> yes, but in my case this doesnt work! I dont know why!

**Comment by jojo12** [comment]
in my case it looks like that:
![selectuser](https://user-images.githubusercontent.com/2960236/218146005-775e8281-b56b-458e-8ede-bb49389b94f2.png)
there is no save possibility!!

**Comment by Heklaterriol** [comment]
Just click on an name, then the modal window should close. 
Does it work?

**Comment by jojo12** [comment]
No, thats the problem it doesnt close

**Comment by Heklaterriol** [comment]
ok, I can reproduce it now

**Comment by jojo12** [comment]
2.3.8 Problem persists!

**Comment by jojo12** [comment]
It works when Jem_smart_search is disabled. Co this seems to be the problem of the plugin.

**Comment by jojo12** [comment]
2.3.9. this problem persists! not fixed

**Comment by jojo12** [comment]
![selectuser](https://user-images.githubusercontent.com/2960236/222175200-29e10c00-9c7d-4f4e-b5cf-2df6de7eee27.png)

**Comment by jojo12** [comment]
Quick solution: add users in frontend!

**Comment by jojo12** [comment]
after the exchange with mckillos files this works fine (but only when JEM smart search disabled!)

**Comment by Heklaterriol** [comment]
Now again – I cannot reproduce it anymore. Difficult to identify, what it is about …

**Comment by jojo12** [comment]
It's very strange:
Even on your JEM4 it is as follow:
When debug (with protocol) is on, then it works best!
But when debug (with protocol) is off, then the modal windows is dead!
I hope, you can reproduce it now!
Perhaps this is a case for @mxckillo

**Comment by Heklaterriol** [comment]
I checked it out:
a jquery library is necessary for it to work.

In debug mode it is loaded, otherwise not.

So these two are needed:
```
/media/vendor/jquery/js/jquery.js
/media/legacy/js/jquery-noconflict.js
```

**Comment by mckillo** [comment]
@Heklaterriol  Do you have the solution (code) for this issue? If it's so, Could you upload it to PR small fixes ? when you can, I and will test it. Thanks.

**Comment by jojo12** [comment]
emergency solution: or enable debug mode or add attending users in frontend!

**Comment by jojo12** [comment]
see
https://forum.joomla.org/viewtopic.php?f=808&p=3643270#p3643276

**Comment by mckillo** [comment]
@jojo12 Jquery included. Works. See commit 8f2de69180a856b90aaca70b9114aefb7b9d018a

**Comment by mckillo** [comment]
@Heklaterriol 2.3.10 version don't include into 
pkg_jem_v2.3.10.zip\pkg_jem_v2.3.10\packages\com_jem.zip\com_jem\admin\views\userelement\view.html.php
the line 16 that resolve this issue:
`HTMLHelper::_('jquery.framework');`
is there other solution about it?
Check it, thank.

**Comment by mckillo** [comment]
@jojo12 The original issue is resolved, but an error has occured with the new version. The reason is that the merge between branchs in Github haven't worked.
