### ISSUE TITLE
frontend>repeating events

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#79]
tested in your jem4
button works ok: after choosing daily, it opens a additional choice!
but when trying to save, there's an error
danger
Save failed with the following error: Incorrect integer value: '' for column `d03b475f`.`jem4_jem_events`.`locid` at row 1

**Comment by Heklaterriol** [comment]
I already sent the bug to the coder.

I forgot to list it here. That is what I sent to him:

**Backend: Repeating events not possible**
It is not possible to create repeating events in the backend
See video clip, first in J4 (not working) and then in J3 (working): [https://jem4.datenablage.info/images/clips/repeating-events.mov
](https://jem4.datenablage.info/images/clips/repeating-events.mov
)

**Comment by jojo12** [comment]
2.3.8: This Problem is fixed! Thanks
