### ISSUE TITLE
Frontend>copy event

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#8]
#1301
Frontend
Calendar>Copy event-->isn’t possible: links to editevent and “Call to a member function format() on bool”
it seems "Copy event" and "Edit event" are the same

**Comment by Heklaterriol** [comment]
when clicking on (the still invisible button) "copy event" I get an error
`components/com_jem/views/editevent/tmpl/edit.php:65`
see also in [issue 49](https://github.com/Heklaterriol/JEM-Project/issues/49)

**Comment by Heklaterriol** [comment]
occurs only in "Legacy (Table Style)"
