### ISSUE TITLE
Frontend>add map link doesn't work

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#81]
there are fields to fill in, but this doesn't work

**Comment by jojo12** [comment]
copy and move coordinates doesn't work

**Comment by jojo12** [comment]
this is in JEM3:
![findby](https://user-images.githubusercontent.com/2960236/218467769-380e6433-e190-4640-8981-9a55a358b6e2.png)

**Comment by jojo12** [comment]
under this there should be other buttons (like in JEM3) which should interfere with venue address on the left side!

**Comment by Heklaterriol** [comment]
I can reproduce it.
But there are other problems too (API Key?), which where already there in JEM 2.

**Comment by Heklaterriol** [comment]
is it possible to use Goolge Maps properly without API Key? 
It would be nice to integrate Open Street Maps. but this would be a new feature –> I open a new issue for further development

**Comment by Heklaterriol** [comment]
is it possible to use Goolge Maps properly without API Key? 
It would be nice to integrate Open Street Maps. but this would be a new feature –> I open a new issue for further development

**Comment by jojo12** [comment]
I tried with my old api key, but this doesn't work. You can use google map in JEM4 with link to google map, possibility 1 and 2. Knowing this, we can let some old relicts. It is more important to finish the rest!

**Comment by jojo12** [comment]
Google uses the address on the left side. works

**Comment by jojo12** [comment]
strange, now google map doesn't work anymore!
