### ISSUE TITLE
Tooltip "Mail to a friend" is not formatted

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#88]
2.3.8. Tooltip "Mail to a friend" is not formatted

**Comment by jobrusche** [comment]
What do you mean with "tooltip not formatted"
Seems to work here :  http://wega.brusche.be/index.php/agenda/event/8:waarneming  
Joomla 4.2.8 / PHP 8.0.23 / JEM beta4 2.3.8

The mail received by the friend looks like this:

This is an email from (WEGA) sent by johan.brusche@gmail.com (johan.brusche@gmail.com). You may also find the following link interesting: http://wega.brusche.be/index.php/aktiviteitenlijst/event/7:waarneming

**Comment by jojo12** [comment]
![tooltipmail](https://user-images.githubusercontent.com/2960236/220687800-a152f645-7e3e-4716-8864-2a4ad735a24a.png)
tooltip is the hint for the button and it is wrong (see image from your site)
the button works fine
