### ISSUE TITLE
Backend Events should be short dateformat!(for tables)

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#89]
In a list like backend events, the weekday is not needed! We can spare place without that!
We should use short format date

**Comment by jojo12** [comment]
means d.m.y

**Comment by Heklaterriol** [comment]
This is a question of JEM Settings.
In the "Format Date" you can ajust the time format to j.m.Y (= dd.mm.yyyy)

We could change the initial settings.

 The general "Format Date" settings is also the default date format for some modules, _if they do not have their settings set._

**Comment by jojo12** [comment]
No, this is not true:
The help page says: 
"Format Date (short):
Use the php date syntax to format the date in short form. This is the format used for **event list views**...."
in other lists like simple list, it is ok,
when I change this, then all the lists have long date form!

**Comment by Heklaterriol** [comment]
Yes this is no contradiction:
The "Format Date (short)" is for "Simple List" – at least it works that way here.

"Format Date" (without "short") is for Backend and default for the modules
in my previous post I was talking about the "Format Date" (without "short").

**Comment by jojo12** [comment]
The help says for
Format Date:
"...This is the format used for event detail views. ...

My proposal for the backend list is to adapt it to the short format date. That means, it should be changed internal in backend>events!
But this is only a proposal to have more place for the other columns.

**Comment by mckillo** [comment]
@jojo12 The solution is change that line to other one: 
`$displaydate = JemOutput::formatDateTime($row->dates, null, $row->enddates, null,'d.m.Y')`;
So, you have the short date format in this event view.

Second point: I have changed order column 1 (id) with column 2 (checkbox),. It's better to have the select checkbox in the column 1, it's more clear and aesthetic.

See commit for this 2 changes: 75bfa760e5f07c76698e2ecb9ee486551d42a996
Testing and If you like it,, can aprove and close the issue (one less).

**Comment by jojo12** [comment]
@mckilllo: 
I propose, it is better:
`$displaydate = JemOutput::formatShortDateTime($row->dates, null, $row->enddates, null); `
which is defined for tables in output.class.php
