### ISSUE TITLE
Frontend>Myevents>Attendees>Print -->no print button

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#90]
in the FRONTEND>My Events> (Attendees) click on number of attendees >you get attendees manager> click on print> you get the print view, but there is no button to print this view!
the other attendees manager on FRONTEND via event>click on number of attendees>click on print --> is the same problem!

In BACKEND via events>attendees>print -->has a text button "print" -->works fine

**Comment by Heklaterriol** [comment]
This is already like this in JEM 2.3.5 – no bug, but a missing feature.

But what I could see as a bug is, that the print template is missing, See #93

**Comment by jojo12** [comment]
Yes, you're right, sorry

**Comment by mckillo** [comment]
I don't see the issue. I have tested print button for attendees of event, it works.

![JEM for JL4 - Print button is working JEM 2 3 9](https://user-images.githubusercontent.com/2765316/222760716-9edc53c8-9301-42cb-94b2-25044165c178.jpg)

What is it wrong? In other view?

**Comment by Heklaterriol** [comment]
It happens just in the **Frontend** and only with the **Legacy (Table Style)**

**Comment by jojo12** [comment]
with mckillos commit

**Comment by mckillo** [comment]
For me, it works in frontend too.

**Comment by jojo12** [comment]
yes, it works!
