### ISSUE TITLE
Backend>Events>Filter: Country ?

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#92]
This does not filter anything. Is this needed?

**Comment by jojo12** [comment]
Ah, I see: When I choose "SWITZERLAND", then the country is "CH".
When I search "CH", I get the right results; when I search "Switzerland" or "SWITZERLAND", I don't get a result.
I didn't know that.

**Comment by Heklaterriol** [comment]
I think we should remove it later. 
Ot, if not, we have to fix it – as it is now, it makes no sense.

**Comment by jojo12** [comment]
Perhaps this needs to be said in help

**Comment by mckillo** [comment]
@jojo12 Check if this is the solution of your issue.
This country filter works only iso2 country string (saved into country field of venue table) and it can't find by name country.
Only add a JOIN of _jem_countries into search filter and link country of venue table with name of country table.

See commit 677fe5bb07c3515021660638f91d598bcc0fced6

**Comment by mckillo** [comment]
Add the proposal to this issue: Add country column to events table (backend - JEM - Events table).
It would be good to have visible the event column by which you are filtering.
So if admin uses search by country, can see the country column too. Admin can stop watching this column (uncheck field).

See the commit to add column e8584c75b5287e6af34c340a77eac48d110e532a

**Comment by jojo12** [comment]
is added. I am not sure if this is really good, because the names of the countries are very extensif! e.g. Switzerland :-)
