### ISSUE TITLE
Modules don't have the time suffix

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#94]
In Jem 3 modules there was the time suffix like 20:00 h! in Jem 4 there is only 20:00! (mod_jem_basic has this not,  but all the rest mod_jem_wide, mod_jem_teaser, mod_jem_banner).
the time suffix should be taken from time settings in jem settings (as in JEM3), or (less wanted) as setting in the modules menues!

**Comment by Heklaterriol** [comment]
coud you provide a screen shot.
In my case it is the same on JEM 3 and JEM 4 – alle modules habe the suffix, except "Module-Basic", there is no extra suffix if not set in the module time format.

**Comment by jojo12** [comment]
I thought, you just changed it!

**Comment by jojo12** [comment]
So I have to say, in my install tion this doesn't work!
