### ISSUE TITLE
Create a category by default when JEM is installed for the first time

### ISSUE THREAD

**Issue by mckillo** [Heklaterriol/JEM-Project#99]
A minor detail to add into new JEM for Joomla 4: Add JEM a category by default (first instalation), for example: Uncategorised, as Joomla has. 

When admin installs JEM for first time can create a new event and it isn't works, you have an error (see jpg file), because there isn't any category selected, the categories list is empty for this first event, unless you previously create a new JEM category.

This same case happens in Joomla. JL has created a default category when you install it by first time. You can create a new article and don't have any error.

It's just an User Experience (UX) improvement to avoid the error that occurs when creating an event on a clean JEM installation.

Solution: In new install, create "Uncategorised" as JEM category by default. For migration, if there are categories created, no create any default [category.]
![Requestcreatecategorybydefault-Voiderrortocreatefirstevent](https://user-images.githubusercontent.com/2765316/220777565-c3421412-a5c5-4174-b87f-b9020113796e.jpg)

**Comment by jojo12** [comment]
it's not needed!
